docs/release-notes/cloud/codacy-now-supports-github-apps.md, docs/release-notes/cloud/removal-of-nodesecurity-golint-and-scsslint.md, docs/release-notes/index.md, mkdocs.yml
The page acting as the release notes index now includes links to the actual release notes pages.
For now, this page is updated manually, but in the future it may be possible to have the page update dynamically when we add new release notes.
Also, this page is a good place to let the users know that we intend to have regular Codacy Cloud release notes in the near future (or, put another way, that we aren't providing release notes for Cloud at the moment).
Here is a preview of the updated page:
https://github.com/codacy/docs/blob/feature/add-release-notes-index/docs/release-notes/index.md
=> feature: Improve release notes index

mkdocs.yml
Solves some of the issues identified by the W3.org validator:
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdocs.codacy.com%2Ffeed_rss_created.xml
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdocs.codacy.com%2Ffeed_rss_updated.xml
=> clean: Improve MkDocs metadata to be used on the RSS feeds

mkdocs.yml
As of now, the plugin doesn't support submodules. I opened a ticket on the GitHub project for the plugin:
Guts/mkdocs-rss-plugin#23
=> fix: Disable MkDocs RSS plugin

docs/index.md
Removes the page "I added a repository" that no longer exists, and adds "Configuring code patters".
The ability to configure the code patterns is important because it allows customers to customize Codacy to their own needs and avoid false positives, which could dilute the value provided by Codacy.
=> feature: Update "Most popular topics" on homepage

.github/workflows/mkdocs.yml
Creates a `robots.txt` file when publishing the "Latest" documentation version on the root of docs.codacy.com.
This is to help prevent old documentation versions from being indexed by search engines, which could pollute the results with outdated pages.
For more background information see https://developers.google.com/search/docs/advanced/robots/intro.
=> feature: Add robots.txt to help prevent indexation of old versions

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/local-analysis/client-side-tools.md
Adds a link to instructions on how to run the client-side tool Faux Pas (https://github.com/codacy/codacy-faux-pas).
#316 should be merged to `master` first.
=> feature: Add link to Faux Pas client-side tool instructions

.github/workflows/mkdocs.yml
We received feedback from some customers that have trouble figuring out which documentation version they should choose, namely if they're using Codacy Cloud.
This pull request tries to make the version switcher more user-friendly by explicitly mentioning the Codacy environment (Cloud or Self-hosted) that each version applies to:
=> feature: Improve usability of version switcher with improved item labels

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/related-tools/local-analysis/client-side-tools.md
@josemiguelmelo, I remembered that we were missing the new Faux Pas tool on one more page! :scream: 
I had the idea of adding comments in the relevant pages that mention tools, reminding us of all the places they must be added.
I still need to implement a solution to avoid having the tools listed on so many pages. :+1:
=> feature: Add Faux Pas to Codacy plugin tools list

.gitmodules, README.md, mkdocs.yml
We're switching to the Codacy MkDocs theme in the public repository [codacy/codacy-mkdocs-material](https://github.com/codacy/codacy-mkdocs-material).
=> feature: Update submodule to use codacy/codacy-mkdocs-material

docs/getting-started/getting-started-with-codacy.md
Adds ignoring files as a suggested step after adding the first repository to Codacy during the "Getting started" tutorial:
=> feature: Suggest how to ignore files in "Getting started with Codacy"

CODE_OF_CONDUCT.md, README.md
Adds the code of conduct, adapted from the latest version of the [Contributor Covenant code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).
=> feature: Add code of conduct DOCS-98

CODE_OF_CONDUCT.md, README.md
I noticed that a couple of links in the code of conduct were outdated.
=> fix: Update links in CODE_OF_CONDUCT.md

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v3.1.0.md
Also updates the submodule chart to the latest commit in the `release-3.1.0` branch.
=> fix: Include release date for Codacy Self-hosted 3.1.0

.github/workflows/link-checker-scheduled.yml, .github/workflows/link-checker.yml, docs/release-notes/self-hosted/self-hosted-v2.0.0.md, docs/release-notes/self-hosted/self-hosted-v2.1.0.md, docs/release-notes/self-hosted/self-hosted-v2.2.0.md, docs/release-notes/self-hosted/self-hosted-v2.2.1.md, docs/repositories-configure/using-submodules.md, mlc_config.json
Substitutes the workflow that uses [peter-evans/link-checker](https://github.com/peter-evans/link-checker) to use [gaurav-nelson/github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check) instead.
The current implementation was reporting too many false positives, mostly related to 429 HTTP errors when checking pages under the github.com domain.
Fixes https://github.com/codacy/docs/issues/342.
=> toolchain: Use gaurav-nelson/github-action-markdown-link-check

docs/faq/general/which-version-control-systems-do-you-support.md
We must list the self-hosted Git provider versions that we support so that we can clearly communicate to customers these requirements while setting up Codacy Self-hosted, and also to help manage expectations when we must ask customers to upgrade their infrastructure. See [DOCS-38](https://codacy.atlassian.net/browse/DOCS-38) for more details.
Once this pull request is merged, we must also merge https://github.com/codacy/chart/pull/649 so that we mention the supported Git providers on the chart [system requirements](https://docs.codacy.com/chart/requirements/).
We should also have a process in place to make sure that we update these minimum versions whenever a change in Codacy Self-hosted requires that. This will also have the advantage of forcing us to make a conscious decision when we're …
=> feature: Add minimum versions of self-hosted Git providers

docs/faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-prs.md
I tried the GitLab instructions on [only allowing merge requests to be merged if the pipeline succeeds](https://docs.gitlab.com/ee/user/project/merge_requests/merge_when_pipeline_succeeds.html#only-allow-merge-requests-to-be-merged-if-the-pipeline-succeeds) and checked that this worked with the external pipeline from the Codacy merge request status:
=> fix: Link to GitLab docs on setting successful pipelines mandatory

docs/index.md, docs/self-hosted/configuring-bitbucket-server-(from-stash)-with-codacy-self-hosted.md, docs/self-hosted/configuring-github-cloud-with-codacy-self-hosted.md, docs/self-hosted/configuring-github-enterprise-with-codacy-self-hosted.md, docs/self-hosted/configuring-gitlab-enterprise-with-codacy-self-hosted.md, docs/self-hosted/configuring-gitlab.com-with-codacy-self-hosted.md, docs/self-hosted/configuring-your-email-server-with-codacy-enterprise.md, docs/self-hosted/create-and-configure-a-new-github-app.md, docs/self-hosted/frequently-asked-questions-(faq).md, docs/self-hosted/gitlab-integration-codacy-self-hosted.md, docs/self-hosted/how-do-i-install-codacy-webhooks-on-github-enterprise.md, docs/self-hosted/how-to-download-logs.md, docs/self-hosted/installing-codacy-self-hosted.md, docs/self-hosted/installing-postgres-for-codacy-self-hosted-using-a-docker-container.md, docs/self-hosted/installing-postgres-for-codacy-self-hosted.md, docs/self-hosted/managing-authentication-for-the-control-panel.md, docs/self-hosted/monitoring-codacy-self-hosted.md, docs/self-hosted/run-spotbugs.md
End of support date for Codacy Self-hosted on Docker as discussed on this [internal document](https://docs.google.com/document/d/1rf2unfm4nw0INYu3AYWZzAiGm3RTrffml5Jk91jAVUM/edit#heading=h.twhlpgv7axax). More background information on this [Slack thread](https://codacy.slack.com/archives/CA5GWEXSN/p1607688085026700).
Adds the following notice at the top of the relevant documentation pages:
=> feature: Mention end of support date for legacy Codacy Self-hosted

CONTRIBUTING.md
This makes it easier for external contributors who may not have set up SSH keys to clone the repository.
=> fix: Use HTTPS to clone repository in CONTRIBUTING.md

mkdocs.yml
Limits the TOC depth to reduce the number of entries on the sidebar for pages with many subsections and improve the usability of the sidebar.
For example, without limiting the TOC depth (also notice that the sidebar doesn't support nesting of section titles):
Limiting the depth, the sidebar only displays the H2 section titles:
=> feature: Limit TOC depth to improve sidebar usability

mkdocs.yml
Reverts #370 and pulls the changes from https://github.com/codacy/codacy-mkdocs-material/pull/11 so that the theme itself limits the heading levels that are displayed on the sidebar.
This solution fixes the broken link detected in https://github.com/codacy/docs/issues/383.
=> fix: Revert #370 and limit section headings directly on theme sidebar

mkdocs.yml
Pulls changes from:
- https://github.com/codacy/codacy-mkdocs-material/pull/12
- https://github.com/codacy/codacy-mkdocs-material/pull/13
The URL for opening a new GitHub issue is not built dynamically from
the configuration on mkdocs.yml.
There is also a new configuration on mkdocs.yml to dynamically enable
(or disable) the user feedback block.
=> feature: Update codacy-mkdocs-material submodule

docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/code-patterns.md
Made the information more structured and also pulled the information about defining the base directory where to start analyzing from the Code Patterns page (in the sequence of #390).
=> clean: Refactor and improve Codacy configuration file

mkdocs.yml
By using JavaScript to dynamically print the copyright year on the footer, we no longer have to remember to update the value of the year.
=> feature: Use JavaScript to print correct copyright year on footer

mkdocs.yml
The page "Default patterns" had been deleted in the meanwhile, but there was no corresponding redirect. This meant that users could still access the old "orphan" page even though it no longer is included in the sidebar navigation.
=> fix: Add missing redirect for deleted page

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
The request from Codacy to have write access to the repository SSH keys is a common objection from customers. This pull request adds a note clarifying how Codacy makes use of the ability to manage SSH keys.
This pull request also removes the "legacy" permissions that Codacy required before using GitHub Apps, as this will simplify the page and make it more straightforward for customers to understand which permissions apply to their scenario (assuming that most accounts, if not all, already migrated to GitHub Apps).
=> feature: Add details about how Codacy performs SSH key management DOCS-183

docs/repositories-configure/codacy-configuration-file.md
The original conversion from the Codacy Knowledge Base to Markdown added spurious escape characters to the glob syntax examples.
=> fix: Remove spurious escape character from glob syntax examples

docs/faq/troubleshooting/not-a-member-of-the-organization.md
The page [Not a member of the organization](https://docs.codacy.com/faq/troubleshooting/not-a-member-of-the-organization/) was heavily outdated since it didn't take into account synced organizations (only legacy "manual" organizations).
This topic should be reviewed again when the improved experience to add people to Codacy is released.
Fixes https://github.com/codacy/docs/issues/41.
=>  fix: Review and update "Not a member of the organization" DOCS-167

.remarkrc
This is to try to avoid false positives when using the [Admonition extension](https://python-markdown.github.io/extensions/admonition/) syntax.
=> toolchain: Force fenced code block style in remark-lint

docs/repositories-configure/codacy-configuration-file.md, docs/repositories/files-view.md
The Codacy configuration file example had a mistake in the syntax for specifying the category Metrics.
This pull request also makes a few small improvements to the documentation page.
Fixes #429.
=> fix: Improve Codacy configuration file documentation DOCS-194

docs/repositories-configure/codacy-configuration-file.md
On https://github.com/codacy/docs/pull/70 we had already reached the conclusion that the Coverage metrics category was not supported on the Codacy configuration file.
However, https://github.com/codacy/docs/pull/436 inadvertently reintroduced Coverage as a supported metrics category.
=> fix: Remove Coverage from Codacy configuration file

docs/repositories-configure/codacy-configuration-file.md
We found out that some instructions in a Codacy configuration file weren't working and opened the issue [CY-3679](https://codacy.atlassian.net/browse/CY-3679) with more details.
=> fix: Remove "metrics:" and "enabled:" from Codacy configuration file

docs/release-notes/cloud/scheduled-maintenance-saturday,-17th-nov@8:00-gmt-(0:00-pst).md, docs/release-notes/cloud/scheduled-maintenance-saturday,-30th-mar@-05:00-gmt-(01:00-edt).md, docs/release-notes/cloud/scheduled-maintenance-saturday,-5th-jan@05:30-gmt-(21:30-pst).md, mkdocs.yml
These pages are no longer useful, and since they don't include the year they may confuse customers who find them by chance and who think the scheduled maintenance is going to happen in the future.
=> clean: Remove scheduled maintenance communications

.github/workflows/codacy-analysis-cli.yml, .github/workflows/mkdocs.yml, .github/workflows/prose.yml
Since now both the codacy/docs and all submodules are public, the PAT is no longer needed. This will make it easier to run the workflows on pull requests coming from forked repositories.
=> toolchain: Stop using secret.PERSONAL_ACCOUNT_TOKEN

.github/workflows/codacy-analysis-cli.yml, .github/workflows/mkdocs.yml, .github/workflows/prose.yml
This reverts commit ded91dc1eaac7c431d2928f71f8edde628040ae0.
It seems that not using the PAT prevents the MkDocs deployment workflow from running.
=> Revert "toolchain: Stop using secret.PERSONAL_ACCOUNT_TOKEN"

docs/repositories-configure/integrations/github-integration.md
Since we're linking directly to the section with details about Suggested fixes when promoting the new feature, this "call to action" can help users enable the setting in their GitHub integration:
=> feature: Add call to action in note for "Suggested fixes"

docs/repositories/security-monitor.md
- Now, [we support SpotBugs](https://docs.codacy.com/related-tools/local-analysis/client-side-tools/) both on Codacy Cloud and Self-hosted.
- "FindBugsSecurity" is actually the SpotBugs plugin [Find Security Bugs](https://find-sec-bugs.github.io/)
- [FindBugs](https://github.com/codacy/codacy-findbugs) no longer seems to be supported
=> fix: Remove Self-hosted limitation for tools in "Security monitor"

docs/repositories-configure/code-patterns.md
Quick improvement regarding #473.
=> fix: Clarify that list only includes tools that support configuration files DOCS-202

docs/faq/general/which-version-control-systems-does-codacy-support.md
Currently, neither the Codacy UI nor the documentation use the exact naming of all Git providers for their SaaS and self-hosted offerings. [This is prone to cause confusion on customers](https://codacy.slack.com/archives/C8X9SS1H7/p1612459507001900).
This is a proposal to update our [documentation page](https://docs.codacy.com/faq/general/which-version-control-systems-does-codacy-support/) listing the supported Git providers with their correct names:
=> feature: Clarify supported Git providers

.github/workflows/mkdocs.yml
This allows testing the generated HTML with wjdp/htmltest also before each deploy.
=> toolchain: Make deployment jobs depend on build

docs/getting-started/getting-started-with-codacy.md
Add a link to the page "Repository Dashboard", to help users who are interested in diving a bit deeper understand the information of the dashboard.
=> feature: Link "Getting started" to "Repository Dashboard"

docs/assets/includes/paid.txt, docs/organizations/managing-repositories.md, docs/repositories-configure/integrations/github-integration.md, docs/repositories/security-monitor.md, mkdocs.yml, requirements.txt
Mark paid features on the documentation with an "info" card that includes a link to the [pricing page](https://www.codacy.com/pricing).
As of now, the features that are marked as paid are the following:
@davidscordeiro @ritagrilo @Gsandec, I would like to have your inputs regarding the copy and any other tweaking that we should do. :+1:
=> feature: Tag paid features DOCS-214

docs/release-notes/self-hosted/self-hosted-v3.3.0.md
The false positive was caused by the removal of the initial "v" in the version number:
https://github.com/codacy/codacy-gosec/commit/cecba6d73e0a26e15ff3246a6cd58962ea41990f
=> fix: Remove spurious Gosec update

docs/assets/includes/api-token-warning.txt, docs/related-tools/codacy-api-tokens.md, docs/related-tools/local-analysis/running-aligncheck.md, docs/related-tools/local-analysis/running-deadcode.md, docs/related-tools/local-analysis/running-spotbugs.md, docs/repositories-configure/integrations/project-api.md
This allows maintaining the warning in a centralized file that is reused where necessary.
=> clean: Move API token security warning to reused include file

docs/organizations/roles-and-permissions-for-synced-organizations.md
In the scope of [CY-3614](https://codacy.atlassian.net/browse/CY-3614), we realized that the documentation should make it clearer that Codacy can't distinguish between the [Bitbucket permission levels](https://confluence.atlassian.com/bitbucketserver/using-repository-permissions-776639771.html) **Read** and **Write**.
This pull request merges the two permission levels in the same table row and clarifies why:
https://github.com/codacy/docs/blob/clean/simplify-bitbucket-permissions-CY-3581/docs/organizations/roles-and-permissions-for-synced-organizations.md
=> clean: Simplify Bitbucket permissions for Read and Write CY-3614

mkdocs.yml
Remove unnecessary quotes from titles in `mkdocs.yml` navigation tree definition. Like this, VS Code highlights the titles, making it easier to identify the documentation sections and edit the tree:
=> clean: Remove unnecessary quotes in mkdocs nav titles

.github/workflows/jira.yml
The same logic to detect user feedback issues and automatically tag them already exists on the documentation links to open new issues, so this step of the CI workflow is not needed.
=> clean: Remove unnecessary step to tag feedback issues

mkdocs.yml
Reverts the changes from https://github.com/codacy/codacy-mkdocs-material/pull/24 and now successfully uses `toc_depth` to limit the heading levels on the navigation sidebar.
This was possible after a fix from MkDocs, see https://github.com/codacy/docs/pull/510#issuecomment-787935847.
=> clean: Update codacy-mkdocs-material

mkdocs.yml
The old page was still available instead of redirecting to the updated URL.
=> fix: Add missing redirect for /related-tools/running-local-analysis/

docs/related-tools/local-analysis/running-local-analysis.md
The documentation page on how to run the CLI had wrong information saying that the `--tool` flag would list the available tools.
While this isn't improved further on [DOCS-200](https://codacy.atlassian.net/browse/DOCS-200), I'm linking to the list of tools in the page [Codacy configuration file](https://docs.codacy.com/repositories-configure/codacy-configuration-file/#which-tools-can-be-configured-and-which-name-should-i-use) instead.
=> fix: The CLI --help flag doesn't list the available tools

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/release-notes/cloud/cloud-release-notes-|-19-october-2018.md, docs/release-notes/cloud/cloud-release-notes-|-29-march-2019.md, docs/release-notes/self-hosted/self-hosted-v2.0.0.md, docs/release-notes/self-hosted/self-hosted-v2.1.0.md, docs/release-notes/self-hosted/self-hosted-v2.1.1.md, docs/release-notes/self-hosted/self-hosted-v2.2.0.md, docs/release-notes/self-hosted/self-hosted-v2.2.1.md, docs/release-notes/self-hosted/self-hosted-v3.0.0.md, docs/release-notes/self-hosted/self-hosted-v3.1.0.md, docs/release-notes/self-hosted/self-hosted-v3.2.0.md, docs/release-notes/self-hosted/self-hosted-v3.3.0.md, docs/repositories-configure/code-patterns.md, docs/repositories-configure/specifying-your-php-version.md
On the official project README the name of the tool is always spelled PHP_CodeSniffer:
https://github.com/squizlabs/PHP_CodeSniffer
=> fix: Use correct name styling for PHP_CodeSniffer

CONTRIBUTING.md
It's best to leave the redirects in place and remove only the lines referencing the release notes.
This way, the redirects under the versioned docs can help the users navigate to the correct pages when switching from an older version to a more recent one.
=> feature: Improve CONTRIBUTING.md on releasing a new version

docs/related-tools/local-analysis/running-local-analysis.md
stumbled upon this, it was here because we used to only support the cli with SH installations and must have fallen through the cracks when we started allowing it for cloud.
for some reason after removing the "for Codacy SH" the sentence now seems weird. is it just me? 😅  (if its not just me, do you have a suggestion?)
=> clean: remove reference to SH in cli docs

docs/getting-started/supported-languages-and-tools.md
SwiftLint includes a rule that reports issues on complex functions:
https://realm.github.io/SwiftLint/cyclomatic_complexity.html
We decided to include SwiftLint under the column **Complexity** on the page [Supported languages and tools](https://docs.codacy.com/getting-started/supported-languages-and-tools/) with a note clarifying this (limited) support for Swift complexity on Codacy.
=>  feature: Mention SwiftLint support for reporting complexity issues DOCS-232

.github/styles/Vocab/Codacy/accept.txt, docs/getting-started/supported-languages-and-tools.md
As a first improvement to make it clearer that Codacy supports a set of infrastructure-as-code frameworks, we can list the frameworks directly in the column **Languages** of the [Supported languages and tools](https://docs.codacy.com/getting-started/supported-languages-and-tools/).
=> feature: List frameworks supported by Checkov CY-4038

docs/release-notes/self-hosted/self-hosted-v3.4.0.md
The possibility of configuring who is allowed to ignore issues across all Git providers was released on this version, but only announced publicly after the release date.
=> fix: Add missing feature to Codacy Self-hosted 3.4.0 release notes

docs/faq/troubleshooting/error-line-endings.md
This pull request adds a "tip" or suggestion on how to find the offending files with CR line endings.
I also organized the troubleshooting process into a numbered sequence of steps to make the process easier to follow:
=> feature: Provide help on how to find the files with CR line endings DOCS-229

.github/workflows/prose.yml
Unsuccessfully tried to solve the following issue that is preventing the vale-action from running:
- https://github.com/actions/http-client/issues/43
- https://github.com/actions/toolkit/issues/747
Even so, it's better to leave the version fixed and let Dependabot update the version when there are new releases.
=> fix: Fix vale-action version to 1.3.0

mkdocs.yml, requirements.txt
Enable RSS feeds for the release notes.
Currently using the fix https://github.com/Guts/mkdocs-rss-plugin/pull/49 from my personal fork of the repository.
=> feature: Enable mkdocs-rss-plugin from branch in personal fork

.github/workflows/prose.yml
Reverts https://github.com/codacy/docs/pull/568
This is necessary for the new option to only check the files that are modified in pull requests to work.
=> toolchain: Update Vale back to the latest (master) version

mkdocs.yml, requirements.txt
The updated version includes the fix from https://github.com/Guts/mkdocs-rss-plugin/pull/49 that allows selecting only the release notes folder, bypassing the [unsupported submodules](https://github.com/Guts/mkdocs-rss-plugin/issues/23).
=> toolchain: Bump mkdocs-rss-plugin to 0.14.0 DOCS-111

docs/release-notes/self-hosted/self-hosted-v3.4.0.md, docs/release-notes/self-hosted/self-hosted-v3.5.0.md
Ordered the issues by descending order of the Jira key and made small adjustments.
=> clean: Review release notes for Codacy Self-hosted 3.5.0

.gitignore, tools/README.md, tools/export-meta-descriptions.py, tools/requirements.txt
Auxiliary tool to export the meta descriptions from the generated HTML pages to a CSV file.
=> toolchain: Add script export-meta-descriptions.py DOCS-227

.remarkrc
On pages that include a YAML front matter remark-lint was suggesting the [setext syntax](http://webcoder.info/markdown-headers.html#the-case-for-setext-headers), probably to be consistent with the separators of the YAML block (---).
=> toolchain: Force remark-lint to check for atx style headings

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Use tables to present the information for each Git provider in a more systematic way that is easier to read:
https://github.com/codacy/docs/blob/clean/codacy-required-permissions/docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Rendered page preview for the GitHub section:
=> clean: Present the permissions required by Codacy using tables

.github/workflows/mkdocs.yml
This should fix the issue of mike failing to push to the protected branch `gh-pages`.
=> fix: Use PAT when deploying with mike to protected branch gh-pages

.github/workflows/mkdocs.yml
This is the recommendation on most resources, only Google suggests all lowercase directives.
=> clean: Uppercase robots.txt directives

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
- Include a link to the [Security Overview](https://security.codacy.com/) to emphasize how Codacy protects the data from customers.
- Mention that each section includes the detailed list of permissions that Codacy requires from each Git provider.
=> clean: Improve introduction of "Which permissions does Codacy need"

.github/workflows/mkdocs.yml
Using the CLI is no longer needed now that Pulse can detect deployments [when pull requests are merged to the default branch](https://docs.pulse.codacy.com/one-click-integrations/#deployment-detection-strategy).
Merge only after the strategy for detecting deployments using pull requests is being used on Pulse.
=> toolchain: Remove redundant Pulse CLI jobs

docs/related-tools/local-analysis/client-side-tools.md
Give visibility to the fact that the Codacy GitHub Action now supports running<sup>*</sup> all client-side tools:
<sup>*</sup>: In fact, the GitHub Action only allows uploading the results for Clang-Tidy and Faux Pas, but this is just a quick improvement for now until I do a [deep refactoring of this documentation](https://codacy.atlassian.net/browse/DOCS-147).
=> feature: Mention Codacy GitHub Action when running client-side tools DOCS-246

docs/codacy-api/api-tokens.md, docs/faq/repositories/how-do-i-reanalyze-my-repository.md, docs/faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-prs.md, docs/faq/troubleshooting/we-no-longer-have-access-to-this-repository.md, docs/getting-started/getting-started-with-codacy.md, docs/getting-started/which-permissions-does-codacy-need-from-my-account.md, docs/index.md, docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/code-patterns.md, docs/repositories-configure/ignoring-files.md, docs/repositories-configure/integrations/bitbucket-integration.md, docs/repositories-configure/integrations/github-integration.md, docs/repositories-configure/integrations/gitlab-integration.md
Review and curate the meta descriptions of the [top landing pages for Google searches](https://docs.google.com/spreadsheets/d/191E8aGjiJwpSp8sroPZQUeZMmSiJ7t2HHLFGnJvkhEE/edit#gid=566714567).
If possible also include the changes to the submodules in this pull request:
- https://github.com/codacy/chart/pull/681
- https://github.com/codacy/codacy-coverage-reporter/pull/314
=> clean: Improve meta descriptions of top searched pages DOCS-227

docs/related-tools/local-analysis/running-aligncheck.md, docs/related-tools/local-analysis/running-deadcode.md, docs/related-tools/local-analysis/running-spotbugs.md
The directive `include-markdown` results in two separate lists on the generated HTML, which breaks the numbering.
Since we were already specifying `rewrite_relative_urls=false`, using the directive `include` is a simple fix.
=> fix: Use "include" directive to avoid breaking the list

mkdocs.yml
Detected by comparing the branch `gh-pages` with the directory `site` generated by MkDocs and finding all orphan pages that were no longer being generated by MkDocs.
=> fix: Add missing redirects

mkdocs.yml
Change permalink character to the more common pound sign (`#`).
=> style: Change permalink character

requirements.txt
Use the fix from https://github.com/datarobot/mkdocs-redirects/pull/21 until it's merged upstream.
=> fix: Update mkdocs-redirects to temporary fix DOCS-249

docs/assets/includes/client-side-tool-instructions.md, docs/related-tools/local-analysis/running-aligncheck.md, docs/related-tools/local-analysis/running-deadcode.md, docs/related-tools/local-analysis/running-spotbugs.md
- Fixes wrong copy-paste from Codacy Coverage Reporter instructions
- The Codacy Analysis CLI doesn't support the environment variables `CODACY_ORGANIZATION_PROVIDER`, `CODACY_USERNAME`, and `CODACY_PROJECT_NAME` and these values must be set using flags instead.
Preview of the changes for SpotBugs:
=> fix: Update client-side tool instructions for using account API tokens CY-3516

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Now we include the information about writing SSH keys on a dedicated section at the bottom of the page.
=> fix: Remove spurious "see box above"

mkdocs.yml
We're currently not using this extension, and besides that, the theme requires tweaking to support the extension better.
=> clean: Disable footnotes Markdown extension

docs/codacy-api/using-the-codacy-api.md
Adds a short section to the Codacy API overview with examples on how to call endpoints that require parameters.
Preview of the new section:
https://github.com/codacy/docs/blob/feature/api-overview-parameters/docs/codacy-api/using-the-codacy-api.md#using-parameters-in-requests
=> feature: Using parameters when calling API endpoints DOCS-245

docs/index.md
This is to match the already updated page [Supported languages and tools](https://docs.codacy.com/getting-started/supported-languages-and-tools/).
=> clean: Mention over 40 supported languages on homepage CY-4038

docs/codacy-api/using-the-codacy-api.md
Adds a section to the Codacy API overview with instructions and an example on how to call endpoints that use pagination.
This page should now mention all the basic mechanics of how to use the Codacy API so that the "end-to-end examples" that I'm going to work on next don't have to explain the basics.
Preview of the new section:
https://github.com/codacy/docs/blob/feature/api-overview-pagination-DOCS-245/docs/codacy-api/using-the-codacy-api.md#using-pagination
=> feature: Using pagination when calling API endpoints DOCS-245

docs/repositories/security-monitor.md
Removes the redundant reference to configuration files for the description of the warning "There are security patterns in this category that are disabled" in https://docs.codacy.com/repositories/security-monitor/#category-states.
The scenario where there are configuration files is covered by a dedicated warning:
For extra context, this feature was last improved on [CY-3684](https://codacy.atlassian.net/browse/CY-3684).
=> fix: Remove spurious reference to configuration files

docs/repositories-configure/quality-settings.md
Mention that the maximum value for the coverage variation in the **Quality settings** page is 1%.
Also adds the clarification of how the settings works for commits.
=> fix: Clarify maximum 1% for coverage variation in Quality settings CY-4370

.github/styles/Vocab/Codacy/accept.txt, docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/repositories-configure/integrations/github-integration.md
Added as supported tool in
- getting-started/supported-languages-and-tools
- related-tools/codacy-plugin-tools
Added as tool with fix suggestions enabled in repositories-configure/github-integration#suggest-fixes
=> feature: add markdownlint as a supported tool CY-4001

.markdownlint.json
This rule generates false positives for indented text inside the admonition blocks.
=> toolchain: Disable markdownlint rule MD046

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/repositories-configure/code-patterns.md
Updates the [table of configuration files](https://docs.codacy.com/repositories-configure/code-patterns/#using-your-own-tool-configuration-files) that Codacy detects and supports for each tool using up-to-date information obtained using the Codacy API endpoint `https://api.codacy.com/api/v3/tools`.
Preview of the updated page:
https://github.com/codacy/docs/blob/fix/configuration-files-DOCS-202/docs/repositories-configure/code-patterns.md#using-your-own-tool-configuration-files
Fixes #473.
=> fix: Update list of supported configuration files DOCS-202

mkdocs.yml
Includes the changes from:
- https://github.com/codacy/chart/pull/690
- https://github.com/codacy/chart/pull/691
=> feature: Update chart submodule

docs/repositories-configure/quality-settings.md
Adds a tip card to the [Quality settings](https://docs.codacy.com/repositories-configure/quality-settings/) page linking to instructions on [how to set Codacy as a required check to merge pull requests](https://docs.codacy.com/faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-prs/):
=> feature: Link quality settings to FAQ on setting required checks

docs/organizations/organization-overview.md, docs/repositories/security-monitor.md
The plugin [mkdocs-meta-descriptions-plugin](https://github.com/prcr/mkdocs-meta-descriptions-plugin) incorrectly grabs the paragraph inside the `<div>` for the "paid feature" admonition.
=> fix: Add explicit meta descriptions to Security Monitor and Organization Overview

docs/faq/general/how-do-i-allowlist-codacy-cloud-on-my-git-provider.md, mkdocs.yml
It's better to be more explicit that this page applies to Codacy Cloud.
=> clean: Mention Codacy Cloud explicitly on allowlisting doc title

docs/repositories/repository-dashboard.md
While working on https://github.com/codacy/docs/pull/751 I noticed that on the Repository Dashboard page we were providing too much information up front, before showing the screenshot of the actual dashboard. This pull request pulls up the screenshot on the page.
=> clean: Adjust screenshot placement on Repository Dashboard page

docs/repositories/security-monitor.md
Fixes https://github.com/codacy/docs/issues/763.
The link to the bundler-audit documentation is no longer working. However, by checking a cached version of the missing page I noticed that it included the contents of the bundler-audit project `README.md`. So it's simpler to just link directly to the GitHub project.
=> fix: Update broken link for bundler-audit

docs/repositories-configure/code-patterns.md
Moves the section "Setting a default configuration for new repositories" down on the page to give more visibility to the instructions on how to import code patterns from another repository.
=> clean: Reorder sections in Code patterns

requirements.txt
This is to avoid unmet dependency issues with mkdocs-rss-plugin, since it doesn't support Jinja2 version 3.x yet.
=> toolchain: Fix Jinja2 version in requirements.txt

docs/repositories-configure/code-patterns.md
Clarifies how to enable using configuration files and how Codacy uses different configuration file versions across branches.
Preview of the updated section:
https://deploy-preview-767--docs-codacy.netlify.app/repositories-configure/code-patterns/#using-your-own-tool-configuration-files
Fixes #690.
=> feature: Clarify how Codacy uses configuration files across branches DOCS-258

requirements.txt
Subsequent versions of mkdocs-material [require mkdocs>=1.2.2](https://github.com/squidfunk/mkdocs-material/commit/f869d275b4926d067b05991945c4fa74a0f1149c#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R22).
However:
-   I haven't tested mkdocs 1.2 thoroughly to ensure the compatibility with all the plugins we're using as well as the custom theme
-   mike still uses mkdocs 1.1 and should be upgraded at the same time
=> toolchain: Limit mkdocs-material version

docs/getting-started/codacy-quickstart.md
This should highlight a bit more the importance of reviewing and adjusting the Quality settings.
=> clean: Mention quality gates in Codacy quickstart

docs/faq/code-analysis/how-to-skip-an-analysis.md, docs/faq/code-analysis/skipping-an-analysis.md, mkdocs.yml
Quick edit to simplify the content of "Skipping and analysis" and include a link to "How do I reanalyze my repository?".
=> clean: Edit and rename "Skipping an analysis"

docs/codacy-api/using-the-codacy-api.md
Before, it wasn't clear how Codacy Self-hosted customers could access the API endpoint reference documentation matching their Codacy Self-hosted version.
Preview of the updated page:
https://deploy-preview-800--docs-codacy.netlify.app/codacy-api/using-the-codacy-api?utm_source=github&utm_campaign=bot_dp
=> clean: Make accessing Codacy Self-hosted API reference more explicit

.github/workflows/vale.yml
Use the new option to only annotate lines changed in pull requests: https://github.com/errata-ai/vale-action#onlyannotatemodifiedlines-default-false
=> toolchain: Tweak Vale workflow and fix GitHub Action version

mkdocs.yml
At some point I removed these redirect pages since they're no longer very useful, however, [Google](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fdocs.codacy.com%2F&item_key=CAMYDSAC&hl=en) is still trying to index the old URLs.
This pull request reinstates redirects to the repository dashboard page.
=> fix: Add old redirects for "Personal dashboard"

mkdocs.yml
Since there were no redirects to override these deleted pages, they were still accessible through their URLs.
=> fix: Add redirects for deleted release notes pages

netlify.toml
Using [this advice](https://answers.netlify.com/t/how-to-use-netlify-only-for-pull-request-previews/11940) to save Netlify build minutes by skipping builds on the `master` branch.
=> toolchain: Skip Netlify builds on the master branch

docs/release-notes/cloud/cloud-2021-08.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud August 2021.
With these release notes we resume the regular publishing of release notes for Codacy Cloud that was interrupted at the end of 2019. :tada:
Live preview of the release notes page:
https://deploy-preview-820--docs-codacy.netlify.app/release-notes/cloud/cloud-2021-08/
=> feature: Release notes for Codacy Cloud August 2021 DOCS-292

docs/assets/includes/service-account-integration.md, docs/faq/troubleshooting/we-no-longer-have-access-to-this-repository.md, docs/faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests.md, docs/repositories-configure/integrations/bitbucket-integration.md, docs/repositories-configure/integrations/github-integration.md, docs/repositories-configure/integrations/gitlab-integration.md
See [DOCS-266](https://codacy.atlassian.net/browse/DOCS-266) for more background info.
Live preview of the page "Why did Codacy stop commenting on pull requests?":
https://deploy-preview-828--docs-codacy.netlify.app/faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests/
Besides this, the pages for each provider integration also recommend using a service account and point to the page above for more details:
- https://deploy-preview-828--docs-codacy.netlify.app/repositories-configure/integrations/github-integration/#enabling
- https://deploy-preview-828--docs-codacy.netlify.app/repositories-configure/integrations/gitlab-integration/#enabling
- https://deploy-preview-828--docs-codacy.netlify.app/repositories-configure/integrations/bitbucket-integration/#enabling
=> feature: Recommend using service account to integrate with Codacy DOCS-266

requirements.txt
After https://github.com/codacy/docs/pull/829 it's redundant to specify the mkdocs-material-extensions dependency since mkdocs-material already handles that transparently.
=> toolchain: Remove redundant mkdocs-material-extensions pip dependency

docs/faq/troubleshooting/why-cant-i-configure-post-commit-hooks-and-integrations.md, docs/repositories-configure/integrations/post-commit-hooks.md, mkdocs.yml
This page is heavily outdated and applies only to manually added repositories in legacy organizations.
I moved the information from this page to a troubleshooting section on the page "Post-commit hooks", which is also heavily outdated but that will be cleaned up and improved at a later time, see https://github.com/codacy/docs/issues/682.
=> clean: Remove page "Why can't I configure post-commit hooks and integrations?"

mkdocs.yml
I missed updating the version value when releasing the new Codacy Self-hosted version 4.2.0, reported by @heliocodacy.
=> fix: Update latest chart version

docs/release-notes/self-hosted/self-hosted-v4.2.0.md
Adds note letting customers know how they can manually activate the bulk copy of patterns feature and apologizing for the issue.
See the internal discussion on [this Slack thread](https://codacy.slack.com/archives/CSSSHAK9N/p1631260385000100?thread_ts=1629727843.001400&cid=CSSSHAK9N).
=> fix: Add note for bulk copy of patterns in Self-hosted 4.2.0

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v4.3.0.md, mkdocs.yml
Adds auto-generated release notes for Codacy Self-hosted 4.3.0
=> feature: Release notes for Codacy Self-hosted 4.3.0

docs/release-notes/self-hosted/self-hosted-v4.2.0.md, docs/release-notes/self-hosted/self-hosted-v4.3.0.md
Ignores Vale error and mentions that the bulk copy feature is already available by default on Codacy Self-hosted 4.3.0.
=> clean: Small adjustments to Self-hosted 4.3.0 release notes DOCS-303

docs/release-notes/cloud/cloud-2019-09-05.md
Fixes one last issue that escaped #856.
=> clean: Fix Markdown syntax issue identified by Codacy

docs/assets/includes/cloud.md, docs/faq/troubleshooting/not-a-member-of-the-organization.md
Even though the error message "Not a member of the organization" may appear on Codacy Self-hosted, in practice it only applies to Codacy Cloud (see [CY-4965](https://codacy.atlassian.net/browse/CY-4965)).
Live preview of the updated page:
https://deploy-preview-858--docs-codacy.netlify.app/faq/troubleshooting/not-a-member-of-the-organization/
=> clean: Clarify that "Not a member of the organization" is only for Cloud CY-4965

docs/organizations/roles-and-permissions-for-synced-organizations.md
These were probably caused by a copy + paste mistake.
=> fix: Remove spurious notes from roles and permissions table

docs/organizations/roles-and-permissions-for-synced-organizations.md
The current role and permissions table is getting too large, and we need to include an extra column for the bulk copy code patterns feature (only available for organization owners).
This pull request refactors the table by merging the columns that have the same permissions and also reorders the columns in a more logical way.
Live preview of the updated page:
* https://deploy-preview-860--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations
Current page for comparison:
* https://docs.codacy.com/organizations/roles-and-permissions-for-synced-organizations/
=> clean: Refactor role and permissions table

docs/organizations/roles-and-permissions-for-synced-organizations.md
When documenting the [bulk copy patterns feature](http://docs.codacy.com/organizations/copying-code-patterns-between-repositories/), I forgot to include it in the [role and permissions table](https://docs.codacy.com/organizations/roles-and-permissions-for-synced-organizations/). This is important because the permissions to use the bulk copy are different from the ones for configuring the code patterns at the repository level.
Live preview of the updated page:
https://deploy-preview-864--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/
=> feature: Add bulk copy patterns to permissions table CY-4340

docs/faq/troubleshooting/we-no-longer-have-access-to-this-repository.md
Codacy only uses the SSH protocol and SSH keys when cloning private repositories. This means that on public repositories, the buttons **Generate New Repository Key** and **Generate New User Key** are not available on the repository settings page.
To help clarify this, this pull request updates the page [We no longer have access to this repository](https://docs.codacy.com/faq/troubleshooting/we-no-longer-have-access-to-this-repository/) to mention that the issue is only relevant for private repositories.
Live preview of the updated page:
https://deploy-preview-863--docs-codacy.netlify.app/faq/troubleshooting/we-no-longer-have-access-to-this-repository
Fixes https://github.com/codacy/docs/issues/838.
=> feature: SSH keys are only used to clone private repositories DOCS-302

docs/repositories-configure/ignoring-files.md, docs/repositories/files.md
Calls attention to the fact that the files that Codacy ignores by default are not visible on the Files page. Fixes #852.
Live preview of the updated section:
https://deploy-preview-870--docs-codacy.netlify.app/repositories/files/#missing-files
=> clean: Mention files ignored by default on Files page DOCS-304

docs/release-notes/cloud/cloud-2021-09.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud September 2021
Live preview: https://deploy-preview-874--docs-codacy.netlify.app/release-notes/cloud/cloud-2021-09/
=> feature: Release notes for Codacy Cloud September 2021

mkdocs.yml
As we still have at least one link on the Codacy UI pointing to the old page, it's better to redirect to the [announcement](https://docs.codacy.com/release-notes/cloud/cloud-2021-11-02-legacy-organizations/) that legacy manual organizations are being discontinued.
=> clean: Redirect "How do I migrate a legacy repository" to EOL announcement CY-4234

docs/release-notes/self-hosted/self-hosted-v4.3.0.md
The automated process failed to find [this change](https://github.com/codacy/codacy-cppcheck/pull/54) for the Self-hosted 4.3.0 release.
=> fix: Add missing release note for CY-4887 to Self-hosted 4.3.0

docs/index.md
Use the same title as the target documentation page.
=> clean: Update title of card for coverage on homepage

docs/release-notes/cloud/cloud-2021-10.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud October 2021
Live preview:
https://deploy-preview-911--docs-codacy.netlify.app/release-notes/cloud/cloud-2021-10/
=> feature: Release notes for Codacy Cloud October 2021 DOCS-294

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/related-tools/local-analysis/client-side-tools.md, docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/configuring-code-patterns.md, docs/repositories/security-monitor.md
I'm adding a comment to make it a bit easier to update all the necessary documentation pages when we add support for a new tool as a temporary measure until [DOCS-165](https://codacy.atlassian.net/browse/DOCS-165) is tackled. See https://github.com/codacy/docs/pull/918#pullrequestreview-800335487.
=> clean: Mention all pages that must be updated when adding a new tool

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/configuring-code-patterns.md
We are adding support the [Spectral](https://stoplight.io/open-source/spectral/) tool which is a generic linter for yaml and json.
At this point we are not supporting user defined configuration files and only our rules.
The rules we included in the system by default are only able to validate [OpenAPI](https://www.openapis.org/) and [AsyncAPI](https://www.asyncapi.com/).
For the table of the supported languages I added sections for those (OpenApi and AsyncAPI) but at the product level when it appears in the Code Patterns we don't have a way to talk about those in specific and the tool appears as supported by Json and Yaml.
So the question here is, should we proceed like this and add these new entries or should approach this differently? It seems we already have similar situation for the …
=> feature: Add Spectral to the tools supported

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/release-notes/cloud/cloud-2018-11-02.md, docs/release-notes/cloud/cloud-2018-11-16.md, docs/release-notes/cloud/cloud-2019-10-30.md, docs/special-thanks.md
=> fix: Update broken links

docs/organizations/using-a-coding-standard.md
Adds a link to the demo video by Harry to the top of the documentation page for the coding standard feature.
Live preview:
https://deploy-preview-933--docs-codacy.netlify.app/organizations/using-a-coding-standard/
=> feature: Link to coding standard demo video CY-4894

docs/assets/includes/coding-standard-apply-important.md, docs/organizations/using-a-coding-standard.md
After introducing the modal window asking for confirmation to apply the coding standard to repositories (https://github.com/codacy/codacy-spa/pull/706), I thought that it could be a good idea to also mention that applying a coding standard overwrites the current settings at the repository level.
This also provides a little bit more information, as it clarifies that it's only the configurations for the tools that are included in the coding standard that are affected:
What do you think @alerizzo @inesgomas @RaquelHipolito?
Live preview:
https://deploy-preview-929--docs-codacy.netlify.app/organizations/using-a-coding-standard/
=> feature: Warn that applying coding standard overwrites existing settings CY-4894

docs/repositories-configure/configuring-code-patterns.md
Following the same approach as for the [Supported languages and tools](https://docs.codacy.com/getting-started/supported-languages-and-tools/) page, I believe it's better to mention the frameworks that Spectral supports instead of the YAML and JSON file formats.
On the Codacy UI the Spectral tool is associated with the YAML and JSON files, but I think this is an additional reason for ensuring that on the documentation we mention AsyncAPI and OpenAPI instead so that users can make the link and understand that Spectral only includes code patterns related to these frameworks and not generic YAML or JSON syntax:
=> clean: Mention frameworks supported by Spectral CY-5214

docs/organizations/using-a-coding-standard.md
It's already possible to rename the coding standard (I forgot to make this update on #945), and the most important feature to be released next is setting the coding standard as default.
=> clean: Update "beta feature" notice on coding standard CY-5213

docs/codacy-api/using-the-codacy-api.md
Currently, all API v3 endpoints that require authentication must use [account API tokens](https://docs.codacy.com/codacy-api/api-tokens/#account-api-tokens).
In the context of [CY-5381](https://codacy.atlassian.net/browse/CY-5381), we thought that it would be useful to mention/clarify this on the documentation.
Live preview of the changed section:
https://61c19d2ca2e42d000748b91a--docs-codacy.netlify.app/codacy-api/using-the-codacy-api/#authenticating-requests-to-the-codacy-api
=> feature: Mention that API v3 only uses account API tokens CY-5381

mkdocs.yml
The page "Why can't I configure post-commit hooks and integrations?" was deleted during the legacy manual organizations cleanup.
Since the redirect is missing, it's still possible to load the old page even though it no longer shows up in the sidebar navigation tree of all other pages:
https://docs.codacy.com/faq/troubleshooting/why-cant-i-configure-post-commit-hooks-and-integrations/
After these changes:
https://deploy-preview-973--docs-codacy.netlify.app/faq/troubleshooting/why-cant-i-configure-post-commit-hooks-and-integrations/
=> fix: Add missing redirect for deleted page CY-4224

docs/codacy-api/api-tokens.md
Updates the Codacy API token documentation to mention that it's possible to create new API tokens either programmatically with the available Codacy API endpoints, or using the Codacy UI.
Live preview:
https://deploy-preview-974--docs-codacy.netlify.app/codacy-api/api-tokens/#project-api-tokens
=> feature: Mention creating API tokens programmatically CY-5352

docs/codacy-api/api-tokens.md
Include the maximum number of project API tokens per repository, as defined on [CY-5355](https://codacy.atlassian.net/browse/CY-5355).
Live preview:
https://deploy-preview-976--docs-codacy.netlify.app/codacy-api/api-tokens/#project-api-tokens
=> feature: Mention maximum of 100 tokens per repository CY-5355

docs/faq/troubleshooting/why-isnt-my-public-repository-being-analyzed.md, docs/release-notes/cloud/cloud-2021-07-03-scheduled-db-maintenance.md
Small edit to fix spelling of "open source".
=> clean: Spell "open source" consistently

docs/release-notes/cloud/cloud-2021-12.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud December 2021
Live preview:
https://deploy-preview-978--docs-codacy.netlify.app/release-notes/cloud/cloud-2021-12/
=> feature: Release notes for Codacy Cloud December 2021

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v5.1.0.md, mkdocs.yml
Adds auto-generated release notes for Codacy Self-hosted 5.1.0
Live preview:
https://deploy-preview-980--docs-codacy.netlify.app/release-notes/self-hosted/self-hosted-v5.1.0/
=> feature: Release notes for Codacy Self-hosted 5.1.0

docs/assets/includes/api-example-pagination-important.md, docs/codacy-api/api-tokens.md, docs/codacy-api/examples/adding-repositories-to-codacy-programmatically.md, docs/codacy-api/examples/creating-project-api-tokens-programmatically.md, docs/codacy-api/examples/obtaining-code-quality-metrics-for-files.md, docs/codacy-api/examples/obtaining-current-issues-in-repositories.md, mkdocs.yml
Adds an example to illustrate the potential of the new API endpoint that allows creating project API tokens.
I also applied minor improvements, consistency edits, and fixes to the existing examples.
Live preview:
https://deploy-preview-985--docs-codacy.netlify.app/codacy-api/examples/creating-project-api-tokens-programmatically/
=> feature: Example for creating project API tokens programmatically CY-5357

docs/release-notes/self-hosted/self-hosted-v5.1.0.md
Updates the Codacy Self-hosted v5.1.0 release notes to link to the new example on how to create project API tokens programmatically.
Live preview:
https://deploy-preview-986--docs-codacy.netlify.app/release-notes/self-hosted/self-hosted-v5.1.0/
=> clean: Link v5.1.0 release notes to project API token example

docs/faq/general/why-cant-i-see-my-organization.md
Now that we only support synced organizations, and most customers should have already migrated to GitHub Apps, we can simplify the troubleshooting for when customers can't see their organizations.
=> clean: Simplify "GitHub Apps" to "GitHub"

.github/workflows/muffet.yml
Following the advice from https://github.com/raviqqe/muffet/issues/172#issuecomment-973944069 to help reduce HTTP 429 errors.
=> toolchain: Lower muffet rate limit to 1

docs/repositories/commits.md
Clarifies why in some situations it's possible for GitHub to list annotations for Codacy issues under the section **Unchanged files with check annotations**.
Live preview :eyes: 
https://deploy-preview-999--docs-codacy.netlify.app/repositories/commits/#possible-issues
=> feature: Mention GitHub's unchanged files with check annotations CY-5344 DOCS-347

docs/repositories-configure/codacy-configuration-file.md
This documentation was initially added on https://github.com/codacy/docs/pull/670 but was later reverted on https://github.com/codacy/docs/pull/906 because the Codacy configuration file settings weren't working.
We can republish the documentation now that [CY-5184](https://codacy.atlassian.net/browse/CY-5184) fixed the issue.
Live preview :eyes: 
https://deploy-preview-998--docs-codacy.netlify.app/repositories-configure/codacy-configuration-file/#pmd-cpd-duplication
=> feature: Document duplication options for PMD CPD CY-5184

docs/repositories-configure/codacy-configuration-file.md
It's better to include the card right after the instructions but before the example, otherwise some users may not see it.
=> clean: Improve visibility of minTokenMatch admonition CY-5184

docs/repositories-configure/adjusting-quality-settings.md
The current double negative between the label mentioning "coverage under" and the negative value introduced by users makes this configuration tricky to understand.
This pull request simplifies the explanation of the setting and adds examples to clarify how to configure the rule for the three possible scenarios: allowing coverage to **decrease**, ensuring that coverage **doesn't decrease**, and enforcing coverage to **improve**.
https://deploy-preview-1005--docs-codacy.netlify.app/repositories-configure/adjusting-quality-settings/#gates
=> clean: Improve explanation of "Coverage variation is under"

mkdocs.yml, requirements.txt
Adds [mkdocs-macros-plugin](https://github.com/fralau/mkdocs_macros_plugin) and removes [mkdocs-markdownextradata-plugin](https://github.com/rosscdh/mkdocs-markdownextradata-plugin).
The macros plugin is more versatile and powerful than the markdownextradata, namely since it allows using variables defined on the page frontmatter.
=> toolchain: Use macros plugin to include variables in Markdown

docs/index.md
Now that we have an end-to-end guide on how to set up Codacy as a quality gate for pull requests, we can promote this use case directly on the homepage using the "most popular topics" cards.
I decided to remove the card for setting up coverage since most users already arrive at that documentation coming from the Codacy UI.
https://deploy-preview-1002--docs-codacy.netlify.app/
=> feature: Add Using Codacy as a quality gate to docs homepage DOCS-342

docs/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate.md
I remembered that ignoring files is another step that is important to avoid getting Codacy results that aren't relevant.
https://deploy-preview-1008--docs-codacy.netlify.app/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate/#adjusting-analysis-settings
=> feature: Ignore irrelevant files before blocking pull requests DOCS-342

docs/getting-started/codacy-quickstart.md
The Codacy quickstart is one of the documentation pages that attracts the most page views, both from new users and prospects who are considering using Codacy.
So, it can be a good idea to give visibility to the use case of using Codacy as a quality gate directly on this page (even though the use case involves a more involved setup).
https://deploy-preview-1009--docs-codacy.netlify.app/getting-started/codacy-quickstart/#all-set
=> feature: Mention blocking pull requests in quickstart DOCS-342

docs/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate.md
Since the section for adjusting the Codacy analysis got a bit bigger, the step for actually deciding and configuring the quality gate rules lacked visibility. This way it is promoted as a "main step" in the overall process.
https://deploy-preview-1012--docs-codacy.netlify.app/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate/
=> clean: Move defining quality gate rules to dedicated section DOCS-342

docs/getting-started/supported-languages-and-tools.md
Resulting from [feedback provided by Harry on Productboard](https://codacy.productboard.com/insights/notes/all-notes/notes/20872259).
Adds a note to Cppcheck on the Supported languages and tools page stating that the tool currently only supports validating the MISRA guidelines for C.
https://deploy-preview-1006--docs-codacy.netlify.app/getting-started/supported-languages-and-tools
=> feature: Mention that Cppcheck only checks MISRA for C

.github/workflows/mkdocs.yml
Makes the CI robust against race conditions when multiple branches are merged to `master` in a short time space.
Read more about the [GitHub Action workflow syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#examples-using-concurrency-and-the-default-behavior).
=> toolchain: Block parallel MkDocs deployments

mkdocs.yml, requirements.txt
**Excludes the release notes pages** from the search index to improve the quality of the search results in some situations, such as when searching for the name of a tool:
=> feature: Exclude release notes from search results

.github/workflows/mkdocs.yml
As we're using more plugins and the complexity of the build process increases, this may become useful to help troubleshoot any issue we may run into in the future.
=> toolchain: Activate verbose output for mkdocs build

.github/workflows/mkdocs.yml, requirements.txt
Bumps mike to the latest version:
https://github.com/jimporter/mike/releases
Since mike >=1.0.0 [no longer supports deploying to the `gh-pages` root](https://github.com/jimporter/mike/issues/49#issuecomment-820625437), this pull request also updates the workflow to use the GitHub Action [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) when deploying the Latest docs version.
- See https://github.com/jimporter/mike/issues/49#issuecomment-820625437 for more details
=> toolchain: Bump mike to latest version DOCS-243

.github/workflows/mkdocs.yml
Reverts https://github.com/codacy/docs/pull/904.
We're now using the latest version of MkDocs, and it's no longer necessary to fix the Python version.
=> toolchain: Revert fix Python version to 3.9.7

.github/workflows/mkdocs.yml, mkdocs.yml
Also fixes the bug of `extra.noindex` being set with the wrong value on the GitHub Action workflow.
=> toolchain: Use MkDocs environment variables for strict and extra.noindex

docs/repositories/commits.md
Clarifies that the colors for the metrics on the commits and pull request pages change as soon as different settings are saved on the Quality settings page.
=> clean: Clarify that metrics colors depends on current gate rules

docs/repositories/commits.md
As discussed on [https://codacy.atlassian.net/browse/CY-5593](https://codacy.atlassian.net/browse/CY-5593), the **Issues** metric only changes color after an update do the quality gate rule if the commit or pull request is reanalyzed. This is in contrast with the remaining metrics, which change as soon as the quality gate rules are saved.
- [Commits page](https://deploy-preview-1043--docs-codacy.netlify.app/repositories/commits/#commit-quality-overview)
- [Pull Requests page](https://deploy-preview-1043--docs-codacy.netlify.app/repositories/pull-requests/#pull-request-quality-overview)
=> clean: Clarify that Issues color only updates after reanalysis CY-5593

mkdocs.yml
We forgot to add the new page to the file `mkdocs.yml` on https://github.com/codacy/docs/pull/1047, so that the page appears on the sidebar navigation:
=> fix: Add missing PMD (Legacy) release notes page to mkdocs.yml CY-5203

docs/codacy-api/examples/adding-repositories-to-codacy-programmatically.md
Increases the waiting time between API calls to add new repositories programmatically on the [example script that we provide](https://deploy-preview-1052--docs-codacy.netlify.app/codacy-api/examples/adding-repositories-to-codacy-programmatically/#example-adding-all-repositories-in-a-github-organization).
=> clean: Increase waiting time between adding repositories CY-5569

requirements.txt
I thought it was something with mu PR but it seems it was a release of markupsafe: https://github.com/pallets/markupsafe/releases/tag/2.1.0
Fixing the previous version
=> toolchain: Fix build error

docs/codacy-api/examples/adding-people-to-codacy-programmatically.md, docs/organizations/managing-people.md
We can unobtrusively highlight the new use case of adding people programmatically using "See also" links and the admonition card on the "Managing people" page. :bulb:
=> feature: Add links to Adding people to Codacy programmatically

docs/repositories/commits.md
Adds a description of the commit/pull request status displayed in the quality overview area. In particular, mentions that the status is always **Up to standards** even if there are no quality gate rules enabled.
See also https://github.com/codacy/docs/pull/1063#issuecomment-1047902860.
=> feature: Describe commit/pull request quality gate status

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v5.0.0.md, docs/release-notes/self-hosted/self-hosted-v5.1.0.md
Adds a section to the Codacy Self-hosted release notes to make all the steps that are necessary for upgrading more explicit.
In particular, this section mentions that it's also necessary to update the command-line tools Codacy Analysis CLI and Codacy Coverage Reporter to the [tagged version](https://github.com/codacy/chart/blob/master/RELEASE.md#4-launching-the-new-release) that corresponds to the new Self-hosted version.
For some extra redundancy, I'm also updating the upgrade instructions directly on the chart docs, see https://github.com/codacy/chart/pull/720.
:arrow_right: After we agree on the format for this new information, I'll also update the release notes for v5.0.0 and update the [script that creates the pull requests for the release …
=> feature: Add section "Upgrading Codacy Self-hosted" to release notes DOCS-355

docs/codacy-api/using-the-codacy-api.md, mkdocs.yml
Adds the OpenAPI definition file URL to the page "Using the Codacy API", and a suggestion to import the definition to help bootstrap integration projects.
This is useful for example when testing the API using tools such as Postman or [Swagger Editor](https://editor.swagger.io/).
See also https://github.com/codacy/codacy-website/pull/112.
https://deploy-preview-1058--docs-codacy.netlify.app/codacy-api/using-the-codacy-api/
=> feature: Add OpenAPI specification URL to "Using the Codacy API" DOCS-353

docs/index.md
Makes the upgrade notice available on the legacy Codacy Self-hosted v2.0.387 more explicit in asking customers that they reach out to us for assistance in migrating to Codacy Self-hosted running on Kubernetes.
Essentially, syncs the messaging with the version that we already have on the [chart documentation](https://docs.codacy.com/chart/):
=> clean: Improve legacy Codacy Self-hosted upgrade notice

.github/workflows/enforce-labels.yml
Use the GitHub Action https://github.com/yogevbd/enforce-label-action to block merging pull requests that have the label `pending release`.
This is useful to help ensure that we don't publish documentation for unreleased features unintentionally.
=> toolchain: Block merging pull requests labeled "pending release"

.github/styles/Vocab/Codacy/accept.txt, .github/workflows/mkdocs.yml, docs/organizations/organization-overview.md, mkdocs.yml
Adds a "feature flag" to help control the visibility of Beta features on the documentation. When deploying the documentation for Self-hosted versions, the flag is set to `false`, thus hiding all Beta features on the Self-hosted documentation.
This pull request also places the changes from #1026 behind the new flag, as per [this decision](https://codacy.slack.com/archives/CA8A4L1DY/p1645788481492139?thread_ts=1645710065.068459&cid=CA8A4L1DY).
=> clean: Control beta feature visibility with environment variable CY-5608

.github/workflows/vale.yml
The configuration option `files` isn't compatible with `onlyAnnotateModifiedLines` at the moment, and apparently, it's ignored.
See https://github.com/errata-ai/vale-action/issues/32.
=> toolchain: Drop Vale configuration option "files"

docs/release-notes/self-hosted/self-hosted-v6.0.0.md
Applies the same format to the already published release notes as the one from https://github.com/codacy/release-notes-tools/pull/82.
=> clean: Improve readability of checking for breaking changes step DOCS-358

.github/workflows/mkdocs.yml, docs/assets/javascripts/version-select.js
The latest version of mike doesn't support using `.` as a version name and fails if the file `versions.json` includes such a version.
Ou version selector drop-down list already uses custom logic to handle the navigation to the latest documentation version, so it's just a matter of using a different version name that doesn't cause mike to fail.
Besides this, this pull request also adds back setting up the Git author since mike requires that to be able to push commits to the `gh-pages` branch.
=> toolchain: Fix versioning mechanism DOCS-243

.github/workflows/mkdocs.yml, docs/organizations/organization-overview.md, mkdocs.yml
Simplify the mechanism to block search indexing on the documentation pages for Codacy Self-hosted versions and controlling the visibility of features by using a single `MKDOCS_SELF_HOSTED` environment variable.
=> toolchain: Use MKDOCS_SELF_HOSTED environment variable

docs/organizations/using-a-coding-standard.md, docs/repositories-configure/configuring-code-patterns.md
Adds "See also" links to the blog post [How to implement Google JavaScript style guide with Codacy](https://blog.codacy.com/implement-google-javascript-style-guide-with-codacy/) on the following related documentation pages:
* [Configuring code patterns](https://deploy-preview-1097--docs-codacy.netlify.app//repositories-configure/configuring-code-patterns/#see-also)
* [Using a coding standard](https://deploy-preview-1097--docs-codacy.netlify.app//organizations/using-a-coding-standard/#see-also)
(Also removes the link to the FAQ page on how to block merging pull requests since that content is not as directly related to configuring code patterns and coding standards as the blog post.)
=> feature: Link to blog post on setting up Google JavaScript style guide

docs/codacy-api/api-tokens.md, docs/organizations/roles-and-permissions-for-synced-organizations.md
It wasn't explicit on the documentation that the account API token only grants access to the same operations as the roles and permissions of the owner of the corresponding account. In particular, uploading coverage using the API token requires specific roles on the Git provider.
- Updated roles and permissions table
https://deploy-preview-1101--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/
- Updates to the API tokens page linking back to the roles and permissions page:
https://deploy-preview-1101--docs-codacy.netlify.app/codacy-api/api-tokens/
=> feature: Account API tokens depend on account permissions CY-5846

docs/getting-started/codacy-quickstart.md
This is just a minor adjustment to the wording on enabling feedback directly on the Git provider pull requests.
=> clean: Adjust wording on enabling Git provider feedback DOCS-361

docs/release-notes/index.md
This is just to help ensure that we don't forget to include the breaking changes from the [ESLint 8 update](https://docs.codacy.com/release-notes/cloud/cloud-2022-04-04-eslint-8-update/) in the next Codacy Self-hosted version.
=> clean: Remind that next Self-hosted version should be a major version CY-5848

mkdocs.yml
Reorders the page [Roles and permissions for synced organizations](https://docs.codacy.com/organizations/roles-and-permissions-for-synced-organizations/) on the navigation sidebar to appear next to the page [Managing people](https://docs.codacy.com/organizations/managing-people/), since the two topics are related.
https://deploy-preview-1115--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/
=> clean: Reorder "Roles and permissions" page on sidebar navigation

docs/getting-started/supported-languages-and-tools.md
Adds a note stating that Codacy currently doesn't support any static code analysis tool capable of analyzing Ruby 3.1 source code.
https://deploy-preview-1118--docs-codacy.netlify.app/getting-started/supported-languages-and-tools#ruby-31
=> feature: Mention that Codacy doesn't support Ruby 3.1 CY-5847

docs/index.md
Small improvement to add clarity to the card "Setting up integrations" on the documentation homepage.
=> clean: Improve description of homepage card "Setting up integrations"

docs/organizations/roles-and-permissions-for-synced-organizations.md
Moves the Bitbucket roles to dedicated lines in the roles and permissions table for the sake of readability and consistency.
https://deploy-preview-1124--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/
=> clean: Expand Bitbucket Read and Write roles into separate lines

requirements.txt
Pins the version of Jinja 2 since the [just released version 3.1.0](https://github.com/pallets/jinja/releases/tag/3.1.0) breaks the MkDocs build:
```
mkdocs -v build
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/codacy/docs/runs/5678155766?check_suite_focus=true#step:5:3).10.2/x6[4](https://github.com/codacy/docs/runs/5678155766?check_suite_focus=true#step:5:4)
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.2/x64/lib
DEBUG    -  Loading configuration file: /home/runner/work/docs/docs/mkdocs.yml
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/mkdocs", line 8, in <module>
sys.exit(cli())
File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1128, in __call__ …
```
=> toolchain: Pin Jinja2 version to 3.0.3

requirements.txt
Since it's not the first time that the MkDocs build starts failing because of Jinja2 updates, it's better to permanently pin this dependency and control when we get updates through Dependabot.
=> toolchain: Clean up pinning of Jinja2 dependency

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Detected by running:
```bash
$ docker run --rm -it   -v $(pwd):/src   klakegg/html-proofer:3.19.2   --allow-hash-href --check-html --empty-alt-ignore --disable-external
Running ["HtmlCheck", "ScriptCheck", "LinkCheck", "ImageCheck"] on ["."] on *.html... 
Ran on 490 files!
- ./getting-started/which-permissions-does-codacy-need-from-my-account/index.html
*  2198:23: ERROR: Character tokens aren't legal here
<cel width="60%"/>
^ (line 2198)
*  2198:5: ERROR: Start tag of nonvoid HTML element ends with '/>', use '>'.
<cel width="60%"/>
^ (line 2198)
*  2199:14: ERROR: Character tokens aren't legal here
</colgroup>
^ (line 2199)
*  2199:1: ERROR: Character tokens aren't legal here
</colgroup>
^ (line 2199)
*  2199:2: ERROR: Character tokens aren't legal here
</colgroup>
^ (line 2199)
* …
```
=> fix: Correct typo in HTML tag

requirements.txt
Also bumps Jinja2 from 3.0.3 to 3.1.1, since the new version of mkdocs fixes the compatibility issues with Jinja2.
=> toolchain: Bump mkdocs from 1.2.3 to 1.2.4

.github/workflows/enforce-labels.yml
The label **don't merge** is more generic and more explicit than the original **pending release**.
=> toolchain: Update label used to block merging pull requests

.github/workflows/enforce-labels.yml
The pull request labels aren't supposed to change when the events `edited` or `synchronized` are triggered, so there's no use in running the GiHub Action.
=> toolchain: Run enforce-label only when necessary

.github/workflows/enforce-labels.yml
Adjusts the changes from https://github.com/codacy/docs/pull/1149.
The event `synchronize` is actually needed - it's also one of the default events that trigger pull request workflows:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
=> fix: Adjust events that trigger the GitHub Action enforce-labels

docs/release-notes/cloud/cloud-2022-03-31-adding-eslint8.md, docs/release-notes/cloud/cloud-2022-04-04-eslint-8-update.md, docs/release-notes/index.md, mkdocs.yml
Adds a release notes page for adding ESLint 8 as a new supported tool and deprecating ESLint 7.
The communication focuses on the changes that customers using configuration files must perform before starting to use ESLint 8.
https://deploy-preview-1155--docs-codacy.netlify.app/release-notes/cloud/cloud-2022-03-31-adding-eslint8/
=> feature: Add ESLint 8 update release notes CY-5848

docs/release-notes/cloud/cloud-2022-03-31-adding-eslint8.md
Completes the last missing step from https://github.com/codacy/docs/pull/1155.
=> feature: Add link to ESLint update on Codacy Community CY-5848

.github/workflows/mkdocs.yml, netlify.toml
This method of having deployment previews isn't as flashy as the built-in one from Netlify but overcomes the limitation of the free 300 CI minutes that Netlify provides.
=> toolchain: Build Netlify deploy previews using GitHub Actions

.github/workflows/mkdocs.yml
One last adjustment over https://github.com/codacy/docs/pull/1165.
=> clean: Use built-in secrets.GITHUB_TOKEN on Netlify deployments

.github/workflows/mkdocs.yml
Apparently, using Netlify aliases with capital letters causes issues making the branch preview deployment unavailable. This ensures that the branch names uses as aliases are lowercase.
=> toolchain: Use lowercase branch names for branch previews

docs/repositories/commits.md
While tackling [CY-5946](https://codacy.atlassian.net/browse/CY-5946) we discovered that the **Files** tab for commits and pull requests also displays all files that received code coverage data in the context of that commit/pull request, and not just the files that were changed in that commit/pull request.
This behavior can change in the future, but I propose that we update the documentation to help set the user's expectations around the way the product currently works.
https://feature-update-files-tab-cy-5946--docs-codacy.netlify.app/repositories/commits/#files-tab
=> feature: The Files tab also includes all files with code coverage CY-5946

.github/workflows/mkdocs.yml
Makes the concurrency group for the mkdocs workflow depend on whether the workflow will update the production environment (i.e. make a push to the `gh-pages` branch) or not.
Uses [this technique](https://github.community/t/possible-to-use-conditional-in-the-env-section-of-a-job/135170/6) to overcome the fact that there is no ternary operator available in GitHub Actions expressions.
=> toolchain: Make concurrency group depend on target environment

docs/organizations/managing-people.md, docs/organizations/roles-and-permissions-for-synced-organizations.md
As the [roles and permissions table](https://docs.codacy.com/organizations/roles-and-permissions-for-synced-organizations/) grew larger, it also became harder to read.
This pull request splits the table across the supported Git providers (making the tables easier to read vertically) and also removes the first column which is no longer necessary (making the tables easier to read horizontally).
Fixes https://github.com/codacy/docs/issues/1163.
https://clean-roles-permissions-readability-docs-368--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/
=> clean: Improve readability of roles and permissions table DOCS-368

docs/organizations/roles-and-permissions-for-synced-organizations.md
GitLab roles can be [for projects](https://docs.gitlab.com/ee/user/permissions.html#project-features-permissions) or [for groups](https://docs.gitlab.com/ee/user/permissions.html#group-members-permissions) (equivalent to GitHub's organizations).
This pull request clarifies that the "Owner" role mentioned is the **group-level** role.
https://clean-clarify-gitlab-roles-cy-5882--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/#permissions-for-gitlab
=> clean: Clarify that GitLab owner role is for groups CY-5882

.github/workflows/mkdocs.yml
The lowercase GitHub Action was missing the condition to ensure it only ran when required.
=> toolchain: Run lowercase GitHub Action only if deploying branch previews

docs/release-notes/cloud/cloud-2022-03.md, docs/release-notes/self-hosted/self-hosted-v7.0.0.md
After https://github.com/codacy/docs/pull/1171 it's now possible to link directly to the GitLab roles and permissions table.
=> clean: Update link to GitLab roles and permissions

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md, docs/getting-started/adding-a-codacy-badge.md, docs/getting-started/supported-languages-and-tools.md, docs/organizations/managing-repositories.md, docs/organizations/organization-overview.md, docs/repositories-configure/adjusting-quality-settings.md, docs/repositories-configure/managing-branches.md, docs/repositories/commits.md, docs/repositories/files.md, docs/repositories/pull-requests.md, docs/repositories/repository-dashboard.md
Adds links throughout the relevant documentation pages to the new page with information on how Codacy calculates metrics, created on #1104.
=> feature: Link to extra info on how Codacy calculates metrics DOCS-25

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
The page didn't mention the average value of the metrics for the repositories displayed on the Organization Overview.
=> fix: Mention averages of metrics on Organization Overview DOCS-25

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
Adds a new link to the blog post [An In-Depth Explanation of Code Complexity](https://blog.codacy.com/an-in-depth-explanation-of-code-complexity/) and also refactors an existing link to the blog.
=> feature: Add link to blog article on code complexity DOCS-25

docs/release-notes/cloud/cloud-2022-03.md, docs/release-notes/self-hosted/self-hosted-v7.0.0.md
Adds links to the changelogs of the updated tools in the latest release notes for Codacy Cloud and Self-hosted (experimental feature from https://github.com/codacy/release-notes-tools/pull/84 and https://github.com/codacy/release-notes-tools/pull/85).
Whenever possible, the links point directly to the correct version on the tool changelogs (for some tools it's not possible to link directly to specific versions in the changelogs).
-   https://feature-add-changelog-updated-tools--docs-codacy.netlify.app/release-notes/cloud/cloud-2022-03/#tool-versions
-   https://feature-add-changelog-updated-tools--docs-codacy.netlify.app/release-notes/self-hosted/self-hosted-v7.0.0/#tool-versions
=> feature: Add links to changelogs of updated tools in release notes DOCS-299

.github/workflows/mkdocs.yml
We hit yet another scenario that caused the Netlify deployments to fail: if the trimmed branch name ends in a special character such as `-`, the alias isn't accepted by Netlify (see https://github.com/codacy/docs/pull/1196).
We were already using too many GitHub Actions just to obtain a sanitized version of the branch name, so I decided to replace them with a sequence of commands that also ensures that the alias doesn't end in a `-` character.
=> toolchain: Use command line to obtain sanitized version of branch name

.github/workflows/mkdocs.yml
I forgot to revert a test while working on #1197! :man_facepalming:
=> toolchain: Correctly obtain branch name from GITHUB_REF

docs/organizations/roles-and-permissions-for-synced-organizations.md
Adds a column to the tables on the "Roles and permissions" page to list the Codacy permission levels that correspond to each role on the Git providers.
This extra mapping is necessary because users need to know the correspondence between the Codacy permission levels and the roles on their Git providers while [configuring the permission levels for changing the analysis configuration](https://feature-map-codacy-permission-level--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/#change-analysis-configuration).
Fixes #1000.
https://feature-map-codacy-permission-level--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/
=> feature: Map Codacy permission levels to Git provider roles DOCS-348

docs/organizations/roles-and-permissions-for-synced-organizations.md
The tables in the [Roles and permissions page](https://docs.codacy.com/organizations/roles-and-permissions-for-synced-organizations/) have become increasingly harder to read as we added more columns for Codacy operations and for the Codacy permission levels (see https://github.com/codacy/docs/pull/1179).
By transposing the tables:
- The columns contain each Git provider role
The number of roles on each Git provider is not expected to increase, and the names of the roles are much shorter than the Codacy operations. This means that the tables don't need to be as wide.
- There is a row for each Codacy operation
This makes it much easier to add new operations if necessary without worrying about the columns becoming too "squished" together.
Before:
After: …
=> clean: Transpose roles and permissions tables DOCS-368

docs/related-tools/local-analysis/client-side-tools.md
Performs a few small cleanups and improvements to the client-side tools page.
(I also considered including the tools in separate sections for containerized and standalone tools, but that would focus the page on the implementation detail and not on the use case of the customers who need to run the tools for the specific languages that they're using.)
https://clean-refactor-client-side-tools--docs-codacy.netlify.app/related-tools/local-analysis/client-side-tools/
=> clean: Small improvements to client-side tools page

docs/assets/includes/coding-standard-apply-important.md, docs/organizations/using-a-coding-standard.md
Adds details on how the coding standard is applied to tools that are using configuration files.
Fixes https://github.com/codacy/docs/issues/1205.
https://feature-coding-standard-config-file--docs-codacy.netlify.app/organizations/using-a-coding-standard/
=> feature: Clarify how coding standard works with configuration files DOCS-371

docs/codacy-api/using-the-codacy-api.md
Clarifies that calling endpoints to retrieve information for public repositories doesn't require authentication.
See @stefanvacareanu7's [comment](https://codacy.atlassian.net/browse/CY-6047?focusedCommentId=49936) for more details on why this is the expected behavior.
https://feature-api-authentication-public-r--docs-codacy.netlify.app/codacy-api/using-the-codacy-api/#authenticating-requests-to-the-codacy-api
=> feature: GET requests for public repositories don't need authentication CY-6047

tools/check-supported-tools.py
Small improvements to the output of the script [check-supported-tools.py](https://github.com/codacy/docs/tree/master/tools#check-supported-tools). Removed the `--verbose` flag and now the script always prints the status of each tool.
=> clean: Improve output of script check-supported-tools.py

tools/README.md, tools/check-security-tools.py, tools/check-supported-tools.py
Adds a simple script to check if the [Security Monitor page](https://docs.codacy.com/repositories/security-monitor/) mentions all supported tools that report security issues.
=> toolchain: Add script to check tools that report security issues DOCS-340

tools/check-security-tools.py, tools/check-supported-tools.py
Ignores the tools that aren't meant to be listed on the documentation in the scripts to check if the tools are up to date. These include a couple of legacy tools and Codacy Scalameta Pro.
After ignoring these tools, it's possible to use the full name of each tool to check if the tool is mentioned in the documentation.
=> toolchain: Ignore tools that aren't listed on documentation

docs/organizations/organization-overview.md
Small refactor to the [Open pull requests section](https://docs.codacy.com/organizations/organization-overview/#open-pull-requests).
Adds a link to the [Pull requests page](https://docs.codacy.com/repositories/pull-requests/#pull-request-status).
https://clean-open-pull-requests-link--docs-codacy.netlify.app/organizations/organization-overview/#open-pull-requests
=> clean: Link Open pull requests section to pull request details page

tools/README.md, tools/get-tool-descriptions.py
Adds a simple script that outputs the description of each supported tool.
This is useful to help ensure that all tools have a description and to review all the descriptions.
=> toolchain: Add script to list all tool descriptions

docs/repositories-configure/codacy-configuration-file.md
Removes `--ignore-identifiers` from the list of default flags that Codacy uses to run PMD CPD.
See [CY-5955](https://codacy.atlassian.net/browse/CY-5955) for more details on why this change was introduced.
https://feature-update-pmd-cpd-defaults-cy--docs-codacy.netlify.app/repositories-configure/codacy-configuration-file/#pmd-cpd-duplication
=> feature: Remove --ignore-identifiers from default PMD CPD options CY-5955

docs/codacy-api/examples/obtaining-code-quality-metrics-for-files.md
Links the API example [Obtaining code quality metrics for files](https://docs.codacy.com/codacy-api/examples/obtaining-code-quality-metrics-for-files/) to the metrics documentation page using a See also link.
https://feature-api-example-see-also-metric--docs-codacy.netlify.app/codacy-api/examples/obtaining-code-quality-metrics-for-files/#see-also
=> feature: Link API example to metrics documentation DOCS-25

docs/repositories-configure/codacy-configuration-file.md
The current example for adding a supported file extension on the Codacy configuration file starts with a hyphen character, which could be confusing to users: `-css.resource`.
It's better to use a simple/common file extension as an example instead.
https://clean-language-file-extension-examp--docs-codacy.netlify.app/repositories-configure/codacy-configuration-file/
=> clean: Update file extension example on Codacy configuration file

docs/release-notes/cloud/cloud-2022-03-31-adding-eslint8.md, docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v7.1.0.md, docs/release-notes/self-hosted/self-hosted-v8.0.0.md, mkdocs.yml
Adds auto-generated release notes for Codacy Self-hosted 8.0.0 ([previously 7.1.0](https://github.com/codacy/docs/pull/1236#discussion_r870406050))
https://feature-release-notes-self-hosted-7--docs-codacy.netlify.app/release-notes/self-hosted/self-hosted-v8.0.0/
=> feature: Release notes for Codacy Self-hosted 8.0.0 DOCS-377

mkdocs.yml
Simplifies the regex used to filter the pages that are included in the RSS feeds.
We already have enough new pages in the created pages RSS feed so as to not let the refactor from https://github.com/codacy/docs/pull/797#issuecomment-907325214 create unwanted entries on the feed.
https://clean-simplify-rss-regex--docs-codacy.netlify.app/feed_rss_created.xml
=> clean: Simplify regex to filter pages included in RSS feeds

.github/workflows/mkdocs.yml
Since all the submodules are now public repositories, we can use the default read-only GitHub token to check out the code in the repository.
=> toolchain: Use read-only token to check out repository

docs/codacy-api/examples/adding-repositories-to-codacy-programmatically.md, docs/faq/general/how-do-i-allowlist-codacy-cloud-on-my-git-provider.md, docs/faq/troubleshooting/error-line-endings.md, docs/getting-started/which-permissions-does-codacy-need-from-my-account.md, docs/organizations/organization-overview.md, docs/repositories-configure/integrations/github-integration.md
Fixes https://github.com/codacy/docs/issues/1241.
=> fix: Update links to moved pages on GitHub documentation

docs/repositories-configure/configuring-code-patterns.md
A customer reported that Codacy only detected `.markdownlint.json` configuration files for markdownlint. We've [checked the code](https://github.com/codacy/codacy-markdownlint/blob/master/src/configCreator.ts) and this is indeed true for now.
See [this Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1653387151450969) for more details.
https://fix-markdownlint-configuration--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/#using-your-own-tool-configuration-files
=> fix: Codacy supports .markdownlint.json configuration files only

docs/organizations/managing-people.md, docs/organizations/roles-and-permissions-for-synced-organizations.md
Clarifies that even though we recommend adding Outside Collaborators / External Users to Codacy to analyze their commits to private repositories, these users can't actually join the organizations on Codacy.
https://clean-external-users-join-org-docs--docs-codacy.netlify.app/organizations/managing-people/
https://clean-external-users-join-org-docs--docs-codacy.netlify.app/organizations/roles-and-permissions-for-synced-organizations/#permissions-for-github
=> clean: Clarify that external users can't join Codacy organizations DOCS-385

.gitignore, tools/check-security-tools.py, tools/check-supported-tools.py
Adds handling for pagination when retrieving the list of code patterns to ensure that all code patterns are checked. This issue was detected while working on https://github.com/codacy/docs/pull/1221.
Also fixes the list of tools that are ignored during the checks.
=> toolchain: Add pagination to check-security-tools.py DOCS-340

.github/CODEOWNERS
Now that I'm no longer part of the @codacy/support group, it's better to include my handle directly in the CODEOWNERS file.
Once we bootstrap a Technical Writing team, we can update the file again to use the handle of the new team.
=> toolchain: Include @prcr directly in CODEOWNERS

docs/repositories-configure/managing-branches.md
The analysis must complete for Codacy to display analysis data and information (such as the files and commits) for that branch.
https://clean-enable-branch-analysis-cy-615--docs-codacy.netlify.app/repositories-configure/managing-branches/
=> clean: Clarify that enabling a new branch triggers a new analysis CY-6154

docs/codacy-api/examples/adding-people-to-codacy-programmatically.md, docs/codacy-api/examples/obtaining-code-quality-metrics-for-files.md, docs/codacy-api/examples/obtaining-current-issues-in-repositories.md
Updates the API examples to use variables to define the Git provider, organization, and repository so it becomes clearer what information the developers must provide themselves.
Applies the feedback from @sampadap03 on https://github.com/codacy/docs/pull/1232.
- [Example: Adding people from a file containing emails](https://clean-api-example-placeholders--docs-codacy.netlify.app/codacy-api/examples/adding-people-to-codacy-programmatically/#example-adding-people-from-a-file-containing-emails)
- [Example: Obtaining security issues with level Error and Warning](https://clean-api-example-placeholders--docs-codacy.netlify.app/codacy-api/examples/obtaining-current-issues-in-repositories/#example-obtaining-security-issues-with-level-error-and-warning)
- [Example: Obtaining security issues with …
=> clean: Use placeholders on API example scripts

tools/check-security-tools.py
Updates the script `check-security-tools.py` to print the number of security patterns supported by each tool. This is to help give a sense of how extensively each tool tests the corresponding programming languages for security issues.
=> toolchain: Print number of security patterns for each tool DOCS-340

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/repositories-configure/configuring-code-patterns.md, tools/check-supported-tools.py
The name of the tool Codacy Scalameta Pro wasn't consistent across the whole documentation, and the link to the project URL on the page [Supported languages and tools](https://docs.codacy.com/getting-started/supported-languages-and-tools/) was wrong.
https://fix-codacy-scalameta-pro--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
https://fix-codacy-scalameta-pro--docs-codacy.netlify.app/related-tools/codacy-plugin-tools/
https://fix-codacy-scalameta-pro--docs-codacy.netlify.app/repositories-configure/codacy-configuration-file/
=> fix: Use the tool name Codacy Scalameta Pro consistently

docs/getting-started/supported-languages-and-tools.md
The official Prospector repository page is https://github.com/PyCQA/prospector, while the previous URL was for a fork of the project to maintain compatibility with Python 2.
https://fix-update-prospector-url--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
=> fix: Update Prospector homepage URL

docs/repositories/security-monitor.md
Adds an intro and formats the descriptions of the Security Monitor categories using a table.
https://clean-format-security-monitor-categ--docs-codacy.netlify.app/repositories/security-monitor/#supported-security-categories
=> clean: Format security monitor categories DOCS-340

docs/faq/general/which-version-control-systems-does-codacy-support.md
Updates the supported GitLab Self-managed version to [14.8](https://docs.gitlab.com/ee/update/#1480).
https://feature-update-gitlab-self-managed--docs-codacy.netlify.app/faq/general/which-version-control-systems-does-codacy-support/
=> feature: Update supported GitLab Self-managed version to 14.8

mkdocs.yml
See https://github.com/codacy/docs/issues/1285 for more details.
https://fix-add-redirect-security--docs-codacy.netlify.app/docs/security/
=> fix: Add redirect from /docs/security/ to security.codacy.com DOCS-390

docs/repositories/security-monitor.md
The red status has precedence over the yellow status on the Security Monitor page:
https://codacy.slack.com/archives/C8X9SS1H7/p1656929862206299
https://codacy.slack.com/archives/C8X9SS1H7/p1656938133466179
This change clarifies the precedence and provides instructions on how the users can obtain the list of disabled code patterns if there are any.
https://feature-clarify-security-monitor-is--docs-codacy.netlify.app/repositories/security-monitor/
=> feature: Clarify precedence of Security Monitor statuses

docs/getting-started/codacy-quickstart.md
Small change to make relevant information more visible by moving it before the corresponding screenshots, as it could easily be missed if users don't scroll past the screenshots.
https://clean-getting-started-swap-info-scr--docs-codacy.netlify.app/getting-started/codacy-quickstart/
=> clean: Move relevant info before corresponding screenshots

docs/release-notes/cloud/cloud-2022-03-31-adding-eslint8.md
As [reported by a customer](https://github.com/codacy/docs/issues/1303), the ESLint 8 migration guide moved to a different URL.
Fixes https://github.com/codacy/docs/issues/1303.
=> fix: Update broken link to ESLint 8 migration guide

docs/assets/includes/dashboard-api-report-note.md, docs/codacy-api/examples/obtaining-code-quality-metrics-for-files.md, docs/codacy-api/examples/obtaining-current-issues-in-repositories.md, docs/organizations/organization-overview.md, docs/repositories/files.md, docs/repositories/issues.md, docs/repositories/repository-dashboard.md
Mention that it's possible to export data from Codacy using the API on relevant pages such as the Issues and Files pages, the Repository Dashboard, and the Organization Overview.
Having a way to export information from the Codacy UI is a typical request from customers. The goal of these changes is to give more visibility to customers that our API supports most of those use cases in a flexible way.
Fixes https://github.com/codacy/docs/issues/1269.
https://feature-mention-api-export-data-doc--docs-codacy.netlify.app/repositories/issues/
https://feature-mention-api-export-data-doc--docs-codacy.netlify.app/repositories/files/
https://feature-mention-api-export-data-doc--docs-codacy.netlify.app/repositories/repository-dashboard/
https://feature-mention-api-export-data-doc--docs-codacy.netlify.a …
=> feature: Mention exporting data from Codacy using the API DOCS-387

docs/faq/general/how-does-codacy-support-gitlab-cloud.md, docs/faq/general/how-does-codacy-support-gitlab-enterprise.md
We make it explicit the limitation, as we never implemented a way to support the [Share projects with other groups](https://docs.gitlab.com/ee/user/project/members/share_project_with_groups.html) feature.
https://codacy.atlassian.net/browse/CY-6349
https://share-projects-group-cy-6349--docs-codacy.netlify.app/faq/general/how-does-codacy-support-gitlab-cloud/
https://share-projects-group-cy-6349--docs-codacy.netlify.app/faq/general/how-does-codacy-support-gitlab-enterprise/
=> Add share project with groups limitations CY-6349

docs/release-notes/index.md
Adds a reminder to mention the changes from https://github.com/codacy/chart/pull/744 in the release notes for the next Codacy Self-hosted version.
=> wip: Add note for next Codacy Self-hosted release

docs/organizations/organization-overview.md
Moves the navigation to the Organization overview to the top of the intro, so that it appears before the screenshot.
https://clean-organization-overview-intro--docs-codacy.netlify.app/organizations/organization-overview/
=> clean: Move navigation to Organization overview

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md, docs/repositories/commits.md, docs/repositories/files.md
Adds explicit descriptions of what are the values that Codacy displays for files in the **Files**, **Commit**, and **Pull request** pages.
See [this Slack thread](https://codacy.slack.com/archives/C03HSK48GDA/p1658745547879439?thread_ts=1658509110.157279&cid=C03HSK48GDA) for the feedback that originated these changes.
- https://feature-clarify-file-coverage-metri--docs-codacy.netlify.app/repositories/files/#file-details
- https://feature-clarify-file-coverage-metri--docs-codacy.netlify.app/repositories/commits/#files-tab
- https://feature-clarify-file-coverage-metri--docs-codacy.netlify.app/repositories/pull-requests/#files-tab
=> feature: Clarify file metrics on Files, Commit, and Pull request pages

.lycheeignore
Ignore links to the private repository codacy/codacy-tools and
a couple of URLs that are rendered dynamically.
Fixes https://github.com/codacy/docs/issues/1339.
=> toolchain: Ignore URLs from link checking

docs/release-notes/cloud/cloud-2022-07.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud July 2022
https://feature-release-notes-cloud-2022-07--docs-codacy.netlify.app/release-notes/cloud/cloud-2022-07/
=> feature: Release notes for Codacy Cloud July 2022 DOCS-331

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
Fixes https://github.com/codacy/docs/issues/1315.
https://fix-issues-page-metrics-docs-401--docs-codacy.netlify.app/faq/code-analysis/which-metrics-does-codacy-calculate/#issues
=> fix: Add missing link to Issues page in Issues metric explanation DOCS-401

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md, docs/repositories-configure/configuring-code-patterns.md, docs/repositories/issues.md
Includes a list of the static code analysis categories supported by Codacy directly on the page [Which metrics does Codacy calculate?](https://docs.codacy.com/faq/code-analysis/which-metrics-does-codacy-calculate/#issues)
Fixes https://github.com/codacy/docs/issues/1316.
https://feat-issue-categories-metrics-docs--docs-codacy.netlify.app/faq/code-analysis/which-metrics-does-codacy-calculate/#issues
=> feat: List issue categories on metrics page DOCS-402

.github/workflows/scheduled.yml
Ignore submodules when compressing images with the [Calibre GitHub Action](https://github.com/calibreapp/image-actions), since those files must be updated directly on the original repositories.
=> toolchain: Ignore submodules when compressing images with Calibre

.github/workflows/scheduled.yml
Use deployment personal access token when creating pull requests for compressing images to enable running the GitHub Actions workflows.
=> toolchain: Use deployment PAT when creating pull request

.lycheeignore
Fixes https://github.com/codacy/docs/issues/1348.
=> toolchain: Fix escape characters in .lycheeignore

docs/repositories-configure/adjusting-quality-settings.md
Codacy doesn't report **commit status** to the Git providers, only pull request status.
For more background, see this [Slack thread](https://codacy.slack.com/archives/C03MFDH8CDV/p1660296375747299).
https://fix-remove-commit-status--docs-codacy.netlify.app/repositories-configure/adjusting-quality-settings/#gates
=> fix: Remove reporting commit status on Git provider

.lycheeignore
Adjusts the regex syntax used in `.lycheeignore` to fix https://github.com/codacy/docs/issues/1357.
=> toolchain: Another attempt to fix .lycheeignore syntax

.github/workflows/vale.yml
Limit the scope of Vale analysis using the option `filter_mode: added`.
=> toolchain: Use Vale filter_mode

docs/account/managing-your-profile.md, docs/organizations/managing-people.md
Removing a member from a GitHub organization on Codacy no longer stops Codacy from analyzing repositories added by that member.
The limitation continues to apply to the other supported Git providers.
- https://clean-remove-people-organization-gi--docs-codacy.netlify.app/organizations/managing-people/#removing-people
- https://clean-remove-people-organization-gi--docs-codacy.netlify.app/account/managing-your-profile/#deleting-your-account
=> clean: Reflect updated GitHub integration on removing people CY-6200

docs/related-tools/local-analysis/client-side-tools.md
Updates the page [Client-side tools](https://docs.codacy.com/related-tools/local-analysis/client-side-tools/) to mention the language(s) that each tool supports.
Fixes #1359.
https://feat-client-side-tool-languages-doc--docs-codacy.netlify.app/related-tools/local-analysis/client-side-tools/#running-the-client-side-tools
=> feat: Include languages supported by client-side tools DOCS-405

docs/faq/general/how-can-i-change-or-cancel-my-plan.md
Fix the end tag for including the information related to the GitHub Marketplace on [How can I change or cancel my plan?](https://docs.codacy.com/faq/general/how-can-i-change-or-cancel-my-plan/)
https://fix-end-github-marketplace--docs-codacy.netlify.app/faq/general/how-can-i-change-or-cancel-my-plan/#if-youre-using-codacy-cloud
=> fix: Correct include-markdown end tag

docs/repositories-configure/integrations/bitbucket-integration.md, docs/repositories-configure/integrations/github-integration.md, docs/repositories-configure/integrations/gitlab-integration.md
Links the notice on each Git provider integration page stating that administrator access to the repository is required to enable the integration to the corresponding roles and permissions tables.
https://feat-link-git-provider-integrations--docs-codacy.netlify.app/repositories-configure/integrations/github-integration/#enabling
https://feat-link-git-provider-integrations--docs-codacy.netlify.app/repositories-configure/integrations/gitlab-integration/#enabling
https://feat-link-git-provider-integrations--docs-codacy.netlify.app/repositories-configure/integrations/bitbucket-integration/#enabling
=> feat: Link Git provider integrations to required roles and permissions

docs/faq/general/how-does-codacy-keep-my-data-secure.md, docs/getting-started/adding-a-codacy-badge.md, docs/repositories/commits.md
Fixes a couple of issues introduced in https://github.com/codacy/docs/pull/1376.
https://fix-ignore-vale-false-positives--docs-codacy.netlify.app/getting-started/adding-a-codacy-badge/
https://fix-ignore-vale-false-positives--docs-codacy.netlify.app/faq/general/how-does-codacy-keep-my-data-secure/
https://fix-ignore-vale-false-positives--docs-codacy.netlify.app/repositories/commits/
=> fix: Correctly ignore Vale false positives on image alt attributes

mkdocs.yml
I discovered that the meta Markdown [Meta-Data extension](https://python-markdown.github.io/extensions/meta_data/) is actually not needed since it's already included in MkDocs.
For more details, see https://github.com/squidfunk/mkdocs-material/issues/4179.
Also opened https://github.com/codacy/pulse-user-docs/pull/125 to clean up the same configuration on `codacy/pulse-user-docs`.
=> infra: Remove unneeded meta Markdown extension

docs/assets/javascripts/version-select.js
Uses static mock JSON to allow the version selector to be rendered even when the file `versions.json` doesn't exist.
This is useful to always render the correct layout of the documentation pages exactly like in the production environment.
https://infra-force-version-list--docs-codacy.netlify.app/
=> infra: Show version selector even if versions.json doesn't exist

docs/faq/code-analysis/does-codacy-place-limits-on-the-code-analysis.md, docs/release-notes/cloud/cloud-2022-03.md, mkdocs.yml
Includes the changes from https://github.com/codacy/codacy-coverage-reporter/pull/409.
https://feat-update-codacy-coverage-reporte--docs-codacy.netlify.app/coverage-reporter/#validating-coverage
=> feat: Update codacy-coverage-reporter submodule CY-6365

docs/repositories-configure/managing-branches.md
The initial default branch on Codacy when adding a new repository is configured according to the default branch on the Git provider.
https://feat-default-branch-git-provider--docs-codacy.netlify.app/repositories-configure/managing-branches/
=> feat: Git provider determines initial default branch on Codacy

docs/assets/includes/api-token-warning.md
Fixes small typo, as suggested by @pSub on https://github.com/codacy/codacy-analysis-cli-action/pull/82.
=> fix: Use correct preposition on API token security warning

.github/workflows/mkdocs.yml
See https://codacy.atlassian.net/browse/DOCS-388?focusedCommentId=50538 for more details on why this was needed.
=> toolchain: Fix GitHub token used to checkout repository

docs/repositories/security-monitor.md
Removes spurious `\` characters from the description of the SQL injection security category.
=> fix: Remove spurious escape characters

docs/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed.md
Links the page [How long does it take for my repository to be analyzed?](https://docs.codacy.com/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed/) to [Codacy's status page](https://status.codacy.com/) to allow users to quickly check if there is an open incident that could delay their analysis.
Relates to #1372.
https://feat-link-status-page--docs-codacy.netlify.app/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed/
=> feat: Add link to Codacy status page

docs/faq/troubleshooting/error-line-endings.md
Mention the diff error message displayed on the Codacy logs UI to help customers find the relevant troubleshooting page.
https://feat-mention-diff-error-message--docs-codacy.netlify.app/faq/troubleshooting/error-line-endings/
=> feat: Mention diff error message displayed on UI

.github/CODEOWNERS
Updates the CODEOWNERS file:
- Adds the new @codacy/docs group (temporary name)
- Removes @codacy/support
=> toolchain: Add Docs group to CODEOWNERS, remove Support

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
Adds an explicit sentence mentioning that the diff coverage calculation doesn't take lines that were deleted in pull requests into account.
https://clean-clarify-diff-coverage-deleted--docs-codacy.netlify.app/faq/code-analysis/which-metrics-does-codacy-calculate/#code-coverage
=> clean: Clarify that diff coverage ignores deleted lines DOCS-413

.github/workflows/scheduled.yml
Use the personal access token `secrets.DEPLOYMENT_PERSONAL_ACCESS_TOKEN` while compressing images with the calibreapp/image-actions GitHub Action.
=> toolchain: Use personal access token while compressing images

CONTRIBUTING.md
This includes two commits:
- the first one brings the docs changes from `codacy/codacy-coverage-reporter` about sending the same report for multiple languages (the version we had there would work 99% of the time but its more correct to send each language as a `partial`)
- the second one adds a new subsection to `CONTRIBUTING.md` to help with bringing changes from submodules (we struggled with this for a bit)
https://fix-coverage-reporter-multiple-lang--docs-codacy.netlify.app/coverage-reporter/uploading-coverage-in-advanced-scenarios/#multiple-languages
=> Fix/coverage reporter multiple languages IO-52

docs/faq/repositories/how-do-i-reanalyze-my-repository.md, docs/organizations/organization-overview.md, docs/release-notes/cloud/cloud-2022-02.md, docs/release-notes/cloud/cloud-2022-05.md, docs/repositories-configure/adjusting-quality-settings.md, docs/repositories/commits.md, docs/repositories/pull-requests.md
Simplifies the anchor links for sections in the commits and pull requests pages.
=> clean: Simplify section anchor links

docs/release-notes/self-hosted/self-hosted-v9.0.0.md
Adds a link in the breaking changes section of the Codacy Self-hosted 9.0.0 release notes to the troubleshooting instructions on how to overcome the MinIO PVC resize.
Fixes https://github.com/codacy/chart/issues/754.
https://feat-troubleshoot-minio-storage-doc--docs-codacy.netlify.app/release-notes/self-hosted/self-hosted-v9.0.0/#breaking-changes
=> feat: Add link to Self-hosted 9.0.0 upgrade troubleshooting DOCS-449

docs/repositories/commits.md
Updates the [pull request](https://docs.codacy.com/repositories/pull-requests/#pull-request-quality-overview) and [commit quality overview](https://docs.codacy.com/repositories/commits/#commit-quality-overview) with links to more detailed information on how Codacy calculates each supported code quality metric.
This is in preparation for linking the Codacy UI to the updated documentation sections (see [IO-101](https://codacy.atlassian.net/browse/IO-101)) and is related to https://github.com/codacy/docs/pull/1452.
- https://feat-link-quality-overview-metrics--docs-codacy.netlify.app/repositories/pull-requests/#quality-overview
- https://feat-link-quality-overview-metrics--docs-codacy.netlify.app/repositories/commits/#quality-overview
=> feat: Link pull request and commit quality overview to extra info DOCS-413 IO-101

docs/repositories-configure/configuring-code-patterns.md
Adds a small clarification to state explicitly that the import code patterns feature doesn't copy tool configuration files across repositories.
Fixes https://github.com/codacy/docs/issues/1308.
- https://clean-import-patterns-config-files--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/#import-patterns
- https://clean-import-patterns-config-files--docs-codacy.netlify.app/organizations/copying-code-patterns-between-repositories/
=> clean: Clarify that importing code patterns doesn't copy config files DOCS-400

requirements.txt
Re-introduce the markdown==3.3.7 dependency pin so that we test new Python Markdown releases before applying them in production [when mkdocs removes the upper version limit](https://github.com/mkdocs/mkdocs/pull/2893).
=> toolchain: Re-pin markdown==3.3.7 dependency

docs/assets/includes/client-side-tool-instructions.md, docs/related-tools/local-analysis/running-aligncheck.md, docs/related-tools/local-analysis/running-deadcode.md, docs/related-tools/local-analysis/running-spotbugs.md
Adds a section at the end of the containerized client-side tool instructions linking to the full list of Codacy Analysis CLI flags. These allow customers to configure how they run the client-side tools and tackle more advanced scenarios.
Fixes https://github.com/codacy/docs/issues/1467.
- https://feat-link-client-side-tools-cli-doc--docs-codacy.netlify.app/related-tools/local-analysis/running-aligncheck/#advanced-configuration
- https://feat-link-client-side-tools-cli-doc--docs-codacy.netlify.app/related-tools/local-analysis/running-deadcode/#advanced-configuration
- https://feat-link-client-side-tools-cli-doc--docs-codacy.netlify.app/related-tools/local-analysis/running-spotbugs/#advanced-configuration
=> feat: Link client side tools to Analysis CLI configurations DOCS-452

docs/repositories-configure/configuring-code-patterns.md
Updates the links to the source code files where users can look up the ESLint plugins that Codacy currently supports.
https://fix-update-eslint-plugin-links--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/#using-your-own-tool-configuration-files
=> fix: Update links to ESLint plugin lists

docs/assets/includes/paid.md, docs/assets/includes/status-checks-important.md, docs/faq/code-analysis/which-metrics-does-codacy-calculate.md, docs/faq/code-analysis/why-does-codacy-show-unexpected-coverage-changes.md, docs/faq/general/how-can-i-change-or-cancel-my-plan.md, docs/faq/general/how-do-i-allowlist-codacy-cloud-on-my-git-provider.md, docs/organizations/changing-your-plan-and-billing.md, docs/organizations/managing-repositories.md, docs/organizations/organization-overview.md, docs/repositories-configure/integrations/bitbucket-integration.md, docs/repositories-configure/integrations/github-integration.md, docs/repositories-configure/integrations/gitlab-integration.md, docs/repositories/security-monitor.md
Refactors the tags used by [mkdocs-include-markdown-plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin) to always use `-start` and `-end` suffixes instead of prefixes so that our usage of the plugin is more consistent and easier to maintain.
This refactoring doesn't create any user-visible changes.
=> clean: Make start and end include tags consistent

.github/workflows/mkdocs.yml
The extra step uploads the generated `meta-descriptions.csv` file as a GitHub Actions workflow artifact so that it's easier to open and inspect the file if necessary.
[Here's an example](https://github.com/codacy/docs/actions/runs/3281263465) for the GitHub Actions run for this branch:
=> toolchain: Upload meta descriptions CSV file as an artifact

docs/repositories-configure/configuring-code-patterns.md
Adds a workaround to allow Codacy to detect ESLint [module-level configuration files](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#cascading-and-hierarchy). Codacy only detects the ESLint configuration files if there's at least a minimal ESLint configuration file **on the root of the repository**.
Fixes #1041
https://feat-eslint-module-config-docs-354--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/#using-your-own-tool-configuration-files
=> feat: Detect ESLint module-level configuration files DOCS-354

.github/workflows/mkdocs.yml
Replaces the `set-output` command, which is now deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See also https://github.com/codacy/pulse-user-docs/pull/141.
=> toolchain: Update netlify-alias GitHub Action step

docs/organizations/changing-your-plan-and-billing.md
Mention the requirement of having enough seats available to let people "join Codacy immediately".
https://feat-joining-seat-availability--docs-codacy.netlify.app/organizations/changing-your-plan-and-billing/#accepting-new-people-to-your-organization
=> feat: Mention seat availability when users join Codacy

docs/related-tools/codacy-plugin-tools.md
The Credo tool was missing a link to the project homepage.
https://fix-credo-add-url--docs-codacy.netlify.app/related-tools/codacy-plugin-tools/
=> fix: Add link to the Credo project on GitHub

docs/release-notes/cloud/cloud-2022-10.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud October 2022
https://feat-release-notes-cloud-2022-10--docs-codacy.netlify.app/release-notes/cloud/cloud-2022-10/
=> feat: Release notes for Codacy Cloud October 2022 DOCS-334

docs/release-notes/cloud/cloud-2022-10.md
Associates the recently closed issue [IO-149](https://codacy.atlassian.net/browse/IO-149) with the corresponding release note. The previous Jira issue was actually that of a research task.
=> clean: Update Jira issue associated with release note

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
Fixes and clarifies the definition of coverage for a repository and coverage variation for commits and pull requests. [See the feedback](https://docs.google.com/spreadsheets/d/1XGFaJrafnhS2Wgfgt498FfPxxPwNrU_CnIqgEOOCUSc/edit?disco=AAAAiuoanO4) from @RaquelHipolito and @fjrdomingues.
https://fix-coverage-variation-definition--docs-codacy.netlify.app/faq/code-analysis/which-metrics-does-codacy-calculate/#code-coverage
=> fix: Clarify definition of coverage and coverage variation

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
Update the references to the commit and pull request page so it uses the singular form since we're actually talking about the page for specific commits or pull requests.
https://fix-singular-commit-pull-request--docs-codacy.netlify.app/faq/code-analysis/which-metrics-does-codacy-calculate/
=> fix: Refer to commit and pull request page using singular

docs/faq/code-analysis/why-does-codacy-show-unexpected-coverage-changes.md
[We were using the wrong nomenclature](https://codacy.atlassian.net/browse/IO-186?focusedCommentId=52313) when referring to the most recent commit in a Git branch.
https://fix-head-commit-nomenclature--docs-codacy.netlify.app/faq/code-analysis/why-does-codacy-show-unexpected-coverage-changes/
=> fix: Rename HEAD commit to head commit

docs/assets/includes/coding-standard-apply-important.md, docs/organizations/using-a-coding-standard.md, docs/repositories-configure/configuring-code-patterns.md, docs/repositories/issues.md
Updates the product behavior when a repository follows a coding standard:
-   The repository now links to the coding standard configurations, instead of copying/overwriting the configurations to the repository
-   Changes made to any tool or code pattern cause the repository to stop following the coding standard, and Codacy copies the coding standard configurations to the repository so users can customize them.
- https://feat-update-following-coding-standa--docs-codacy.netlify.app/organizations/using-a-coding-standard/
- https://feat-update-following-coding-standa--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/
- https://feat-update-following-coding-standa--docs-codacy.netlify.app/repositories/issues/#ignoring-and-managing-issues
=> feat: Update behavior when using a coding standard PLUTO-98

docs/repositories-configure/adjusting-quality-settings.md
Adjusts the order for presenting the intervals used to configure the coverage variation quality gate so that the most common setting (allowing the coverage to decrease) is the first one.
https://clean-coverage-variation-intervals--docs-codacy.netlify.app/repositories-configure/adjusting-quality-settings/#gates
=> clean: Adjust order of coverage variation quality gate intervals

docs/coverage-reporter/alternative-ways-of-running-coverage-reporter.md, docs/coverage-reporter/index.md, docs/release-notes/self-hosted/self-hosted-v9.0.0.md
Self-hosted customers must make sure that they're using a version of the Codacy Coverage Reporter that is compatible with their Codacy instance.
- https://feat-coverage-reporter-sh-version-d--docs-codacy.netlify.app/coverage-reporter/#uploading-coverage
- https://feat-coverage-reporter-sh-version-d--docs-codacy.netlify.app/coverage-reporter/alternative-ways-of-running-coverage-reporter/
=> feat: Use Coverage Reporter version compatible with Self-hosted instance DOCS-484

docs/coverage-reporter/alternative-ways-of-running-coverage-reporter.md
See https://github.com/codacy/codacy-coverage-reporter/pull/419
https://feat-interactive-alternative-run-ex--docs-codacy.netlify.app/coverage-reporter/alternative-ways-of-running-coverage-reporter/#bash-script
Reply to and close https://github.com/codacy/codacy-coverage-reporter/pull/419 after deploying this.
1. Create a directory, say `mkdir /path/to/dir`, and place the 2 files below in it (`Dockerfile` and `test-upload.sh`). You'll also need a sample coverage file (not included here).
2. In `Dockerfile`, update the `WORKDIR /path/to/dir` line with the actual path to your new directory.
3. In `test-upload.sh`, update the `./coverage.xml` path with the actual path to a test coverage file.
4. Navigate to the new directory `cd /path/to/dir`.
5. Build the `test-upload` image: `docker build …
=> feat: Update alternative run examples to be interactive

docs/release-notes/cloud/cloud-2022-11.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud November 2022
https://feat-release-notes-cloud-2022-11--docs-codacy.netlify.app/release-notes/cloud/cloud-2022-11/
=> feat: Release notes for Codacy Cloud November 2022

.vale.ini, docs/organizations/roles-and-permissions-for-organizations.md
@prcr 
I'm creating this to fix an issue we noticed with Vale incorrectly detecting ignored blocks:
```
text here would sometimes not be ignored!
```
Upon opening a pull request on the Vale repo, the author suggested that I send over the `.vale.ini` file, where I noticed a suspicious regex match under `TokenIgnores`, `<.*>`, which would match HTML comments too.
Here's an attempted fix. It does fix our ignore issue, but I'm not quite sure what that regex matching rule was there for initially, so some context could be useful for a final sanity check before merging this one.
Thanks!
=> fix: Vale - ignored block checked incorrectly

docs/assets/stylesheets/version-select.css
Fixes excessive header select width, which pushed the CTA off-screen.
See: 
* https://github.com/codacy/codacy-mkdocs-material/pull/71
* https://github.com/codacy/codacy-mkdocs-material/pull/69
=> fix: Mobile header select max width

CONTRIBUTING.md
Markdown doesn't support [description lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl), but we should have a convention for encoding information that fits the format of "term/details" pairs.
https://github.com/codacy/docs/blob/feat/contributing-description-lists/CONTRIBUTING.md#markdown-conventions
=> feat: Add guidelines for encoding description lists

docs/repositories/repository-dashboard.md
Clarifies that the information that Codacy displays on the **Coverage** area of the repository dashboard is based on the coverage goal defined in the quality settings of the repository.
https://clean-coverage-area-quality-setting--docs-codacy.netlify.app/repositories-configure/adjusting-quality-settings/#goals
=> clean: Clarify that info in Coverage area is based on the coverage goal DOCS-436

docs/assets/includes/status-checks-important.md, docs/repositories-configure/integrations/gitlab-integration.md
This is a small cleanup to make the name of an included Markdown block more explicit and parallel with the other existing block ` [...] `.
=> clean: Rename included Markdown block

docs/coverage-reporter/index.md
A user may push coverage reports while on a branch that's not being analyzed. Opening a PR for that branch fixes the issue.
We should clarify to the user that a PR should be open.
https://feat-improve-troubleshooting-branch--docs-codacy.netlify.app/coverage-reporter/#status-branch-not-enabled
=> feat: Improve status-branch-not-enabled troubleshooting message DOCS-489

docs/assets/includes/status-checks-important.md
The Git provider integration pages were missing a reference to the newly introduced quality gate rule **Diff coverage is under** when letting users know that they must have a coverage quality gate rule for Codacy to post status checks on pull requests.
- https://fix-mention-diff-coverage--docs-codacy.netlify.app/repositories-configure/integrations/github-integration/#status-checks
- https://fix-mention-diff-coverage--docs-codacy.netlify.app/repositories-configure/integrations/gitlab-integration/#pull-request-status
- https://fix-mention-diff-coverage--docs-codacy.netlify.app/repositories-configure/integrations/bitbucket-integration/#pull-request-status
=> fix: Mention missing "Diff coverage is under" quality gate rule

docs/getting-started/supported-languages-and-tools.md, docs/repositories-configure/configuring-code-patterns.md, docs/repositories/security-monitor.md
According to the changes suggested in https://github.com/codacy/docs/pull/1564, the correct spelling of the Sonar OSS tools are SonarC# and SonarVB.
This pull request ensures that we use the correct spelling consistently.
=> fix: Update the spelling of SonarC# and SonarVB

.github/styles/Vocab/Codacy/accept.txt
See https://github.com/codacy/pulse-user-docs/pull/167#discussion_r1062613135 for the rationale for removing these spurious words.
=> toolchain: Remove spurious words from the Vale accept list DOCS-479

.codacy.yml
Excludes the path `.github/styles` from the Codacy analysis to prevent false positive issues on "3rd party" files.
=> toolchain: Ignore Codacy analysis on Vale styles DOCS-479

.github/workflows/mkdocs.yml
While working on https://github.com/codacy/pulse-user-docs/pull/173, @claudiacarpinteiro and I noticed that the workflow on this repository wasn't actually updating the file `robots.txt` depending on the `CUSTOM_DOMAIN` variable. The `robots.txt` worked only because the workflow doesn't clean the files on the `gh-pages` branch on each deploy.
This fixes the issue [using the same solution](https://github.com/codacy/pulse-user-docs/pull/173#discussion_r1067214430) used on codacy/pulse-user-docs.
=> toolchain: Update robots.txt depending on CUSTOM_DOMAIN DOCS-455

.github/workflows/mkdocs.yml
The changes from the previous pull request https://github.com/codacy/docs/pull/1578 didn't work because we were creating the `robots.txt` file in the wrong directory. The idea is to create the file inside the directory `./site` where all the generated HTML files are so that it's pushed together with them to the branch `gh-pages`.
Besides that, I had copied Pulse's domain name by mistake! :sweat_smile:
=> toolchain: Fix generating robots.txt file DOCS-455

docs/organizations/using-a-coding-standard.md
These are some quick edits to decouple generic improvements from the multiple coding standards task at https://github.com/codacy/docs/pull/1577
https://feat-tweak-cs-page-io-352--docs-codacy.netlify.app/organizations/using-a-coding-standard/
=> feat: Tweak coding standards page IO-352

docs/repositories-configure/integrations/github-integration.md
Complements the changes from https://github.com/codacy/docs/pull/1546 by mentioning the new coverage summaries in the page meta description.
https://feat-coverage-summary-meta-descript--docs-codacy.netlify.app/repositories-configure/integrations/github-integration/
=> feat: Mention coverage summaries in meta description COV-19

.markdownlint.json
The markdownlint [MD051 rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md051---link-fragments-should-be-valid) reports false positives whenever we explicitly define an ID for section titles that is different from the "automatically generated" ID and link to them. On the other hand, we already have a step in our CI/CD checking for broken link fragments, so it's safe to turn off this rule.
=> toolchain: Disable markdownlint rule MD051

docs/coverage-reporter/uploading-coverage-in-advanced-scenarios.md
Adds a missing `!` to fix the admonition syntax on the page "[Uploading coverage in advanced scenarios](https://docs.codacy.com/coverage-reporter/uploading-coverage-in-advanced-scenarios/#multiple-reports)".
https://fix-update-admonition-syntax--docs-codacy.netlify.app/coverage-reporter/uploading-coverage-in-advanced-scenarios/#multiple-reports
=> fix: Update admonition syntax

docs/faq/code-analysis/how-to-skip-an-analysis.md
We support 2 other tags that are included in the docs - `[codacy skip]` and `[skip codacy]`.
This change adds these 2 to the other already documented.
https://vascorsd-add-other-skip-tags--docs-codacy.netlify.app/faq/code-analysis/how-to-skip-an-analysis/
=> Include other tags that can skip commits

docs/coverage-reporter/index.md
The previous version assumed that the only supported metric was the coverage variation. The rewrite makes the text more generic, and also takes into account that now the pull request page displays a warning message instead of `-` when the metrics aren't available.
https://fix-missing-coverage--docs-codacy.netlify.app/coverage-reporter/#validating-coverage
=> fix: Update reference to missing coverage metrics

docs/codacy-api/examples/adding-people-to-codacy-programmatically.md, docs/codacy-api/examples/adding-repositories-to-codacy-programmatically.md, docs/codacy-api/examples/creating-project-api-tokens-programmatically.md, docs/codacy-api/examples/obtaining-code-quality-metrics-for-files.md, docs/codacy-api/examples/obtaining-current-issues-in-repositories.md
These are very minor edits to improve the consistency and simplify referring to API endpoints in the examples, which I noticed while starting to work on https://github.com/codacy/docs/pull/1596.
=> clean: Simplify references to API endpoints in examples DOCS-503

.github/workflows/scheduled.yml
The syntax for correctly testing the lychee-action exit code changed some time ago in https://github.com/lycheeverse/lychee-action/pull/167.
We detected that our workflow was no longer working correctly [while setting up the workflow on codacy/pulse-user-docs](https://github.com/codacy/pulse-user-docs/pull/184#issuecomment-1403493362).
=> toolchain: Fix testing the lychee exit code DOCS-507

docs/codacy-api/examples/identifying-commits-without-coverage-data.md, mkdocs.yml
Adds an example on how to use the Codacy API endpoint [getPullRequestCoverageReports](https://api.codacy.com/api/api-docs#getpullrequestcoveragereports) to determine if Codacy is missing coverage data that is required to calculate the coverage metrics for pull requests.
https://feat-api-example-pr-reports-docs-50--docs-codacy.netlify.app/codacy-api/examples/identifying-commits-without-coverage-data/
=> feat: API example to check for PR commits with missing coverage data DOCS-503

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md
Fixes https://github.com/codacy/docs/issues/1600.
=> fix: Update broken links to CoffeeLint homepage

docs/codacy-api/examples/creating-project-api-tokens-programmatically.md, docs/codacy-api/examples/identifying-commits-without-coverage-data.md
Adds an API example to create a project token for just one repository.
https://feat-create-single-project-token-do--docs-codacy.netlify.app/codacy-api/examples/creating-project-api-tokens-programmatically/#example-creating-a-project-api-token-for-a-single-repository
=> feat: Add API example for creating single project token DOCS-514

docs/codacy-api/examples/creating-project-api-tokens-programmatically.md
Adds an API example to retrieve the existing API tokens for a repository.
https://feat-list-project-api-tokens-docs-5--docs-codacy.netlify.app/codacy-api/examples/creating-project-api-tokens-programmatically/#example-listing-the-project-api-tokens-for-a-repository
=> feat: Add API example for retrieving project API tokens DOCS-514

docs/getting-started/configuring-your-repository.md
Briefly mention the security monitor in the onboarding guide. See this [Jira comment](https://codacy.atlassian.net/browse/DOCS-470?focusedCommentId=54083) for context.
https://feat-mention-security-monitor-docs--docs-codacy.netlify.app/getting-started/configuring-your-repository/#configuring-code-patterns
=> feat: Mention security monitor DOCS-470

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
we no longer fallback to creating user keys when we fail to create a repository key
@machadoit commented that he had recently changed this behavior when troubleshooting a bug
the change was originally introduced in codacy/portal#156
https://fix-user-ssh-reasons--docs-codacy.netlify.app/getting-started/which-permissions-does-codacy-need-from-my-account/#why-does-codacy-ask-for-permission-to-create-ssh-keys
=> fix: update user ssh keys behaviors PLUTO-120

docs/coverage-reporter/uploading-coverage-in-advanced-scenarios.md
The link was no longer pointing to the start of the array of language strings.
=> fix: Update link to supported language strings

docs/coverage-reporter/alternative-ways-of-running-coverage-reporter.md, docs/release-notes/self-hosted/self-hosted-v10.0.0.md, docs/release-notes/self-hosted/self-hosted-v9.0.0.md
Bumps the Codacy Coverage Reporter version mentioned in the Codacy Self-hosted 9.0.0 and 10.0.0 release notes to match the version that the script `get.sh` downloads (see https://github.com/codacy/codacy-coverage-reporter/pull/454).
For more details, see [this internal Slack thread](https://codacy.slack.com/archives/C04QBKNQQD7/p1677154426013459?thread_ts=1677132105.912619&cid=C04QBKNQQD7).
=> feat: Bump Codacy Coverage Reporter for Self-hosted 9.0.0 and 10.0.0 COV-35

docs/coverage-reporter/alternative-ways-of-running-coverage-reporter.md
The Codacy Coverage Reporter Java binary now works with any recent Java version (see https://github.com/codacy/codacy-coverage-reporter/pull/453), so it's no longer a requirement to use Java 8.
For more information see [this internal Slack thread](https://codacy.slack.com/archives/CQESXTUHW/p1677083736235449).
=> feat: Codacy Coverage Reporter .jar no longer requires Java 8 TS-261

docs/related-tools/local-analysis/running-local-analysis.md
Codacy no longer supports the tools FindBugs nor FindSecBugs, so we're removing the references to these tools.
=> fix: Remove spurious references to FindBugs and FindSecBugs DOCS-138

mkdocs.yml
Adds a redirect to overwrite the page "[How do I block merging pull requests using Codacy as a quality gate?](https://docs.codacy.com/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate/)", which was deleted in https://github.com/codacy/docs/pull/1584 but is still live in production.
=> fix: Add missing redirect for deleted page "How do I block merging ..."

docs/faq/code-analysis/why-does-codacy-show-unexpected-coverage-changes.md, docs/repositories-configure/adjusting-quality-settings.md
Introduces a prescriptive recommendation for the coverage variation gate threshold.
:arrow_right: I'm using a recommendation of -5.00% to -1.00% as a placeholder for now, but we should agree on the final range that we recommend.
- https://feat-recommend-coverage-variation-g--docs-codacy.netlify.app/repositories-configure/adjusting-quality-settings/#gates
- https://feat-recommend-coverage-variation-g--docs-codacy.netlify.app/faq/code-analysis/why-does-codacy-show-unexpected-coverage-changes/#example-pull-request-coverage-variation-is-negative-but-no-files-have-coverage-variation
=> feat: Recommend coverage variation gate threshold range COV-239

docs/release-notes/self-hosted/self-hosted-v10.0.0.md
These changes are being made because of [this question](https://codacy.slack.com/archives/C011BCR2RN3/p1678270209392439) from @debgalser.
While addressing [DOCS-484](https://codacy.atlassian.net/browse/DOCS-484) (see also [this Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1669706073958519) for all the details) we substituted the `self-hosted-*` tags with hardcoded CLI versions.
However, since the issue only affected the Codacy Coverage Reporter, nothing should prevent us from supporting a more recent version of the Codacy Analysis CLI.
[DOCS-484]: https://codacy.atlassian.net/browse/DOCS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Update Codacy Analysis CLI version compatible with SH 10.0.0

docs/repositories/repository-dashboard.md
Fixes the navigation instructions to the Repository Dashboard, which were incorrectly linking to the Organization Overview (and calling it the Organization Dashboard!).
https://fix-repository-dashboard-navigation--docs-codacy.netlify.app/repositories/repository-dashboard/
=> fix: Fix and simplify navigation instructions to Repository Dashboard

docs/repositories/commits.md
Applies @nicklem's feedback in https://github.com/codacy/docs/pull/1658#discussion_r1159890969 to the original "Commits" and "Pull requests" pages:
- https://style-commits-present-tense--docs-codacy.netlify.app/repositories/commits/#files-tab
- https://style-commits-present-tense--docs-codacy.netlify.app/repositories/pull-requests/#files-tab
=> style: Use present tense on Commits and Pull requests pages

docs/getting-started/supported-languages-and-tools.md, docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/configuring-code-patterns.md
Reflects the changes from https://github.com/codacy/codacy-tools/pull/495 on the documentation.
- https://feat-rename-pylint-legacy--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
- https://feat-rename-pylint-legacy--docs-codacy.netlify.app/repositories-configure/codacy-configuration-file/#which-tools-can-be-configured-and-which-name-should-i-use
- https://feat-rename-pylint-legacy--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/#using-your-own-tool-configuration-files
=> feat: Rename Pylint tools PLUTO-530

docs/organizations/managing-people.md
Clarifies the behavior specific for private repositories, which could be interpreted as Codacy's general behavior. (see [this comment](https://github.com/codacy/docs/pull/1666/files#r1163809024))
https://clean-clarify-private-repo-analysis--docs-codacy.netlify.app/organizations/managing-people/
=> clean: Clarify behavior for private repositories PLUTO-368

docs/repositories-configure/ignoring-files.md
Currently, it's not possible to ignore files just for the coverage metrics calculation using the Codacy configuration file (see the internal Slack threads [1](https://codacy.slack.com/archives/C011BCR2RN3/p1681741447370729) and [2](https://codacy.slack.com/archives/C8X9SS1H7/p1681809603610739)).
However, the page [Ignoring files](https://docs.codacy.com/repositories-configure/ignoring-files/) mentioned that the Codacy configuration file could exclude files just for coverage.
This pull request removes the references to capabilities of the Codacy configuration file from the page, so that all information about what's possible to do using the Codacy configuration file is centralized on the page [Codacy configuration file](https://docs.codacy.com/repositories-configure/codacy-configuration-file …
=> fix: Remove wrong Codacy config file capabilities from Ignoring files DOCS-548

docs/repositories/commits.md
While working on https://github.com/codacy/docs/pull/1658 I noticed that we have a reference to "issues on other branches", when in fact it makes more sense to say "commits on other branches".
https://clean-branch-commits--docs-codacy.netlify.app/repositories/commits/
=> clean: Reference commits on different branches

docs/repositories/files.md
Small edit to make a reference to "branches that are enabled and analyzed by Codacy" consistent with both the UI and the rest of the documentation, and to tweak the instruction to "click on a specific file".
I noticed these improvement opportunities while working on https://github.com/codacy/docs/pull/1658 (https://github.com/codacy/docs/pull/1658/commits/c8024137a54db06a6347be270d266dc1f3e47236).
https://clean-enabled-branches--docs-codacy.netlify.app/repositories/files/
=> clean: Change "active branches" to "enabled branches"

docs/repositories/pull-requests.md
Mentions that it's possible to click a commit from the list of commits on the pull request page to navigate to the details of that commit.
I had the idea for this improvement while working on https://github.com/codacy/docs/pull/1658 (https://github.com/codacy/docs/pull/1658/commits/6fb2d5cc8bd9459e8d3c49c6ff4d9b713604b9c5).
https://feat-link-commit-details--docs-codacy.netlify.app/repositories/pull-requests/#commits-tab
=> feat: Add link to commit details

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v11.0.0.md, mkdocs.yml
Adds auto-generated release notes for Codacy Self-hosted 11.0.0
https://feat-release-notes-self-hosted-11-0--docs-codacy.netlify.app/release-notes/self-hosted/self-hosted-v11.0.0/
=> feat: Release notes for Codacy Self-hosted 11.0.0

docs/coverage-reporter/index.md
We need to manually bump the Codacy Coverage Reporter version compatible with the latest version of Codacy Self-hosted. See [this Slack message](https://codacy.slack.com/archives/CSSSHAK9N/p1682068927434349?thread_ts=1680622175.515419&cid=CSSSHAK9N) for more context.
=> feat: Bump CODACY_REPORTER_VERSION for Self-hosted 11.0.0 DOCS-543

docs/assets/includes/paid.md
This issue was affecting the page https://docs.codacy.com/faq/general/how-do-i-allowlist-codacy-cloud-on-my-git-provider/
https://fix-close-end-comment--docs-codacy.netlify.app/faq/general/how-do-i-allowlist-codacy-cloud-on-my-git-provider/
=> fix: Close end comment on paid.md include

docs/coverage/repositories/commits.md, docs/coverage/repositories/repository-dashboard.md
Fixes the broken links that were caused by merging the changes from `master` into `dev/coverage`.
=> fix: Update broken links after Gates and Goals split PLUTO-532

docs/release-notes/cloud/cloud-2023-04.md, docs/release-notes/index.md, mkdocs.yml
Adds auto-generated release notes for Codacy Cloud April 2023
https://feat-release-notes-cloud-2023-04--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-04/
=> feat: Release notes for Codacy Cloud April 2023 DOCS-440

docs/organizations/using-coding-standards.md
Clarifies that repositories can only follow one coding standard at a time.
https://feat-clarify-one-cs-per-repo--docs-codacy.netlify.app/organizations/using-coding-standards/
=> feat: Clarify that repositories can follow one CS at a time DOCS-551

docs/getting-started/codacy-quickstart.md
The onboarding process no longer includes the sign-up form (see [this internal Slack thread](https://codacy.slack.com/archives/CM9E1BT7V/p1681823732606879)).
=> clean: Remove reference to sign-up form

.github/workflows/mkdocs.yml, mkdocs.yml
Sets the MkDocs variable `pull_request_preview` to trigger an automatic banner at the top of all pages for pull request previews  (see https://github.com/codacy/codacy-mkdocs-material/pull/82).
https://toolchain-pr-preview-notice--docs-codacy.netlify.app/
=> toolchain: Add automatic banner to all pages in pull request previews

docs/organizations/what-are-organizations.md
* Clarifies how to manually synchronize an organization name if it doesn't do so automatically.
* Rewords the existing sentence slightly to improve the flow.
https://feat-org-name-sync-button-docs-558--docs-codacy.netlify.app/organizations/what-are-organizations/#updates-on-the-git-provider
=> feat: Clarify how to synchronize an org name DOCS-558

docs/coverage-reporter/alternative-ways-of-running-coverage-reporter.md
[As identified by a customer](https://codacy.slack.com/archives/C011BCR2RN3/p1684919257267609), we were still mentioning an older Codacy Coverage Reporter version on the page [Alternative ways of running Coverage Reporter](https://docs.codacy.com/coverage-reporter/alternative-ways-of-running-coverage-reporter/).
We failed to update this reference to the version number in the pull request https://github.com/codacy/docs/pull/1696.
https://fix-bump-codacy-coverage-reporter-v--docs-codacy.netlify.app/coverage-reporter/alternative-ways-of-running-coverage-reporter/
=> fix: Bump Codacy Coverage Reporter version for SH 11.0.0 DOCS-543

.vale.ini, CONTRIBUTING.md, docs/coverage-reporter/alternative-ways-of-running-coverage-reporter.md, docs/coverage-reporter/index.md, mkdocs.yml
Uses an MkDocs variable to keep the version of the Codacy Coverage Reporter compatible with the latest Codacy Self-hosted version. Also refactors the name of the existing variable `extra.version` to make it more explicit.
The idea is to help prevent situations where we fail to update all references to the Codacy Coverage Reporter version across the documentation (see https://github.com/codacy/docs/pull/1742 as an example).
- https://toolchain-coverage-reporter-version--docs-codacy.netlify.app/coverage-reporter/#uploading-coverage
- https://toolchain-coverage-reporter-version--docs-codacy.netlify.app/coverage-reporter/alternative-ways-of-running-coverage--reporter/
=> toolchain: Use variable for hardcoded Codacy Coverage Reporter version

docs/organizations/using-coding-standards.md
On https://github.com/codacy/docs/pull/1735#discussion_r1202400533 we realized that the [coding standards documentation](https://docs.codacy.com/organizations/using-coding-standards/) is interspersed with small bits of information explaining how the feature works.
Although some information can be conveniently disclosed right next to the instructions where it's more relevant, the remaining details should be clearly explained directly on the conceptual part of the page.
https://clean-refactor-coding-standards-doc--docs-codacy.netlify.app/organizations/using-coding-standards/
- We already use **apply** and **follow** consistently, depending if we're talking about applying a coding standard to a repository or about a repository that is following a coding standard. :+1:
=> clean: Refactor details on how coding standards work DOCS-556

.lycheeignore
Ignores a new dynamic link that was introduced in https://github.com/codacy/docs/pull/1743.
Fixes https://github.com/codacy/docs/issues/1747.
=> toolchain: Ignore dynamic link to Coverage Reporter

docs/release-notes/cloud/cloud-2021-12.md, docs/release-notes/cloud/cloud-2022-01.md, docs/release-notes/cloud/cloud-2022-02.md, docs/release-notes/cloud/cloud-2022-03.md, docs/release-notes/cloud/cloud-2022-04.md, docs/release-notes/cloud/cloud-2022-05.md, docs/release-notes/cloud/cloud-2022-06.md, docs/release-notes/cloud/cloud-2022-07.md, docs/release-notes/cloud/cloud-2022-08.md, docs/release-notes/cloud/cloud-2022-09.md, docs/release-notes/cloud/cloud-2022-10.md, docs/release-notes/cloud/cloud-2022-11.md, docs/release-notes/cloud/cloud-2022-12.md, docs/release-notes/cloud/cloud-2023-01.md, docs/release-notes/cloud/cloud-2023-02.md, docs/release-notes/cloud/cloud-2023-03.md, docs/release-notes/cloud/cloud-2023-04.md, docs/release-notes/self-hosted/self-hosted-v10.0.0.md, docs/release-notes/self-hosted/self-hosted-v11.0.0.md, docs/release-notes/self-hosted/self-hosted-v5.1.0.md, docs/release-notes/self-hosted/self-hosted-v6.0.0.md, docs/release-notes/self-hosted/self-hosted-v7.0.0.md, docs/release-notes/self-hosted/self-hosted-v8.0.0.md, docs/release-notes/self-hosted/self-hosted-v8.1.0.md, docs/release-notes/self-hosted/self-hosted-v9.0.0.md
The release notes script was failing to obtain the correct "pretty name" of the Spectral tool due to a glitch (see https://github.com/codacy/codacy-spectral/pull/9).
=> fix: Update the name of the tool Spectral on the release notes pages DOCS-441

docs/repositories/files.md
While watching [this Coverage demo](https://codacy.slack.com/archives/C026D0HN6/p1687169081742529?thread_ts=1687165910.748659&cid=C026D0HN6) @fjrdomingues mentioned that a customer asked what was the meaning of the line background color of the **Diff** tab for a file.
https://feat-coverage-diff-color--docs-codacy.netlify.app/repositories/files/#file-details
=> feat: Clarify line colors on file Diff tab

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
I noticed by chance that a couple of links were outdated.
https://fix-update-revoke-integration-links--docs-codacy.netlify.app/getting-started/which-permissions-does-codacy-need-from-my-account/#revoking-access-to-integrations
=> fix: Update 3rd party links for revoking integrations

docs/organizations/managing-security-and-risk.md
Fixes an oversight where we call the "Security managers" area in the UI using the old name, "Permissions".
https://fix-rename-security-manager-permiss--docs-codacy.netlify.app/organizations/managing-security-and-risk/#assigning-the-security-manager-role
=> fix: Rename Security Manager permission area

docs/getting-started/supported-languages-and-tools.md, docs/release-notes/cloud/cloud-2022-07.md, docs/release-notes/cloud/cloud-2023-01.md, docs/release-notes/cloud/cloud-2023-03.md, docs/release-notes/cloud/cloud-2023-04.md, docs/release-notes/cloud/cloud-2023-05.md, docs/release-notes/self-hosted/self-hosted-v11.0.0.md, docs/release-notes/self-hosted/self-hosted-v9.0.0.md, docs/repositories/security-monitor.md, docs/special-thanks.md
[While working on the Self-hosted release notes](https://github.com/codacy/docs/pull/1767#discussion_r1259711770) we noticed that the GitHub repositories for Prospector had moved to a different organization. While searching for `PyCQA` I noticed that the URLs for Pylint also had redirects. This pull request updates all relevant URLs to the newest repositories for the tools.
=> fix: Update URLs for the Prospector and Pylint tools

mkdocs.yml
This was causing issues that prevented testing the built site on MacOS since the filesystem there is case insensitive.
=> toolchain: Remove redirects from /Chart to /chart

docs/repositories-configure/integrations/github-integration.md
Clarify when AI auto-fixes are used
[AI-enhanced comments (GitHub)](https://feat-clarify-when-ai-not-used-docs--docs-codacy.netlify.app/repositories-configure/integrations/github-integration/#ai-enhanced-comments)
=> feat: Tweak copy to clarify when we use AI fixes DOCS-581

docs/organizations/managing-security-and-risk.md
A quick fix to move the section "Managing access to security and risk management" of the SRM page further up and reestablish the concept/task/reference structure of the page.
[Managing access to security and risk management](https://feat-reorder-srm-sections--docs-codacy.netlify.app/organizations/managing-security-and-risk/#managing-access-to-security-and-risk-management)
=> feat: Reorder SRM page sections

docs/release-notes/cloud/cloud-2023-07.md
Tweaks the email deduplication release note to be more accurate.
https://clean-tweak-deduplication-note-docs--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-07/#product-enhancements
=> clean: Tweak email deduplication release note for accuracy DOCS-443

docs/repositories-configure/removing-your-repository.md
Adds a note to the [Removing your repository](https://docs.codacy.com/repositories-configure/removing-your-repository/) page indicating to remove the resources from the Git provider after removing the repository.
The message is aligned with [the UI](https://github.com/codacy/codacy-spa/pull/1256/files).
https://docs-575-manual-actions-when-removi--docs-codacy.netlify.app/repositories-configure/removing-your-repository/
=> clean: Add note to Remove repository page DOCS-575

docs/getting-started/supported-languages-and-tools.md, docs/release-notes/cloud/cloud-2023-10-13-bundler-audit-deprecation.md, docs/release-notes/cloud/cloud-2023-10-16-bundler-audit-deprecation.md, docs/release-notes/index.md, docs/repositories-configure/configuring-code-patterns.md, docs/repositories/security-monitor.md, mkdocs.yml
* Removes references to bundler-audit
* Adds a deprecation release note page
https://tarot-2399-doc-update-docs-bundler--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-10-13-bundler-audit-deprecation/
=> feat: Deprecate bundler-audit TAROT-2399 

docs/getting-started/supported-languages-and-tools.md
Adds a column to the supported tools table with dependency vulnerability scans.
* [Supported languages and tools](https://tarot-2398-doc-update-docs-trivy-no--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/#supported-languages-and-tools)
[TAROT-2333]: https://codacy.atlassian.net/browse/TAROT-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add dependency vulnerability scans to supported tool table TAROT-2398

docs/organizations/roles-and-permissions-for-organizations.md
Clarifies that a Repository Admin on GitHub can only add or remove repositories on Codacy if an Organization Owner has given the Codacy GitHub App access to those repositories.
https://docs-604-clarify-add-repo-permissio--docs-codacy.netlify.app/organizations/roles-and-permissions-for-organizations/#permissions-for-github
=> clean: Clarify requirement to add or remove repository on GitHub DOCS-604

docs/repositories-configure/managing-branches.md
Updates the [Managing branches](https://docs.codacy.com/repositories-configure/managing-branches/) page to include not supported branch names (Git reserved terms).
This update follows the change made in [this pull request](https://github.com/codacy/repository-listener/pull/531).
https://feat-invalid-branch-names--docs-codacy.netlify.app/repositories-configure/managing-branches/
-   [x] Wait for feature release
=> feat: Add note for branches reserved names IO-830

docs/getting-started/supported-languages-and-tools.md, docs/release-notes/cloud/cloud-2023-10-24-csslint-jshint-fauxpas-tailor-tslint-deprecation.md, docs/release-notes/cloud/cloud-2023-10-25-csslint-jshint-fauxpas-tailor-tslint-deprecation.md, docs/release-notes/index.md, docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/configuring-code-patterns.md, docs/repositories-configure/local-analysis/client-side-tools.md, docs/special-thanks.md, mkdocs.yml
Deprecates some tools.
https://docs-609-deprecate-tools--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-10-25-csslint-jshint-fauxpas-tailor-tslint-deprecation/
=> feat: Deprecate tools DOCS-609

docs/faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests.md
Removes the link to GitHub integration that doesn't make sense anymore, as the page content applies only to GitLab and Bitbucket.
https://pluto-772-remove-gh-integration-lin--docs-codacy.netlify.app/faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests/
=> clean: Remove link to GitHub integration PLUTO-772

docs/repositories-configure/local-analysis/client-side-tools.md
Fixes a table formatting issue on the [Client-side tools](https://docs.codacy.com/repositories-configure/local-analysis/client-side-tools/) page.
https://fix-client-side-tools-fix-table-for--docs-codacy.netlify.app/repositories-configure/local-analysis/client-side-tools/
=> fix: Fix formatting on client-side tools table  

docs/getting-started/supported-languages-and-tools.md
Adds an admonition to clarify that security checks happen when users commit to a repo.
[Supported languages and tools](https://docs-610-clarify-that-tools-run-onl--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/)
=> feat: Add admonition clarifying when security checks are run DOCS-610

docs/release-notes/cloud/cloud-2023-10.md
Tweaks a release note to clarify that the new Coverage report setting will be active by default soon.
https://feat-update-release-note--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-10/#product-enhancements
=> feat: Update release note

tools/check-security-tools.py, tools/check-supported-tools.py
Duplicates the edits in https://github.com/codacy/docs/pull/1950, which has some trouble with the `mkdocs` build process.
=> toolchain: Update list of tool UUIDs to ignore DOCS-613

docs/organizations/managing-repositories.md
Clarify that the Follow is automatic only for Organization admins, not Organization managers, members, or anyone with Repository Admin permissions.
also, disregard who adds the repository: the auto follow happens always. when an organization admin adds it, or via API, or by repository admins.
=> fix: clarify how auto-follow works

docs/organizations/managing-repositories.md
Adds a tip with the option to unfollow a repository using the Codacy API.
https://docs-611-unfollow-repository-via-ap--docs-codacy.netlify.app/organizations/managing-repositories/#adding-a-repository
=> clean: Unfollow repository via API DOCS-611

.github/styles/Vocab/Codacy/accept.txt, docs/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks.md, docs/release-notes/index.md
Updates the new Coverage engine release note to give users more visibility on the updates to different features, which will happen over some months.
* [New Coverage engine](https://docs-623-update-the-structure-of-ne--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks/)
=> feat: Update the structure of new Coverage engine release note DOCS-623

docs/getting-started/supported-languages-and-tools.md, docs/index.md, docs/repositories/security-monitor.md
Update the use of the term "framework" to prevent confusion when browsing the relevant pages.
- Decision: declined for now. let's revisit this in the future if more requests emerge in this sense. It's a sizable effort.
=> feat: Update the use of "framework" DOCS-615

.github/workflows/mkdocs.yml
Temporarily pins Python version to avoid a build error.
=> fix: Fix Python version

docs/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks.md
Adds an extra note for people that are looking for 'problems' regarding summary not showing up. Can check a bit more on slack as well https://codacy.slack.com/archives/CA5GWEXSN/p1702578148626289
https://extra-note-summary--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks/#rollout-of-new-coverage-engine-november-23-2023
=> Extra note on summary from new coverage

docs/faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests.md
Updates FAQs with instructions to fix missing coverage summaries on GitHub PRs.
https://docs-629-missing-coverage-informati--docs-codacy.netlify.app/faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests/
=> feat: Instructions to fix missing coverage summaries DOCS-629

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md
Improve the Security category description to highlight available features.
https://docs-627-improve-the-description-of--docs-codacy.netlify.app/faq/code-analysis/which-metrics-does-codacy-calculate/#issues
=> feat: Update the Security category description DOCS-627

.github/workflows/vale.yml, docs/faq/troubleshooting/error-line-endings.md
Temporarily pin Vale version to fix a regression introduced by the update to 3.0.0 (see [release notes](https://github.com/errata-ai/vale/releases/tag/v3.0.0))
=> fix: Move Vale setting files

.github/workflows/mkdocs.yml
Unpin the Python version to confirm the issue addressed in https://github.com/codacy/docs/pull/1976 is now fixed.
=> tooling: Unpin Python version

docs/coverage-reporter/troubleshooting-coverage-cli-issues.md
Documents the "No coverage data was sent" error.
Note: also sorts page sections alphabetically and adds an intro section with links. For the relevant edit, see https://github.com/codacy/docs/pull/2011/commits/d77c651a8f71fbae49e7c95b2503e44be2f934c5.
https://docs-645-clarify-that-the-coverage--docs-codacy.netlify.app/coverage-reporter/troubleshooting-coverage-cli-issues/#no-coverage-data-was-sent
=> feat: Document the "No coverage data was sent" error DOCS-645

docs/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks.md
Formats and adds entries to the table for all planned updates.
https://ala-845-p1-doc-update-release-note--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks/
=> feat: Prep rlease note for latest updates ALA-845

docs/release-notes/cloud/cloud-2024-01.md
Applies the feedback received on #2029 for [Cloud January 2024 release notes](https://docs.codacy.com/release-notes/cloud/cloud-2024-01/).
=> fix: Fix release note typos DOCS-630

docs/organizations/managing-security-and-risk.md
Clarifies that the "Not yet categorized" category is temporary, offering a solution to recategorize affected issues. See [thread](https://codacy.slack.com/archives/C01DLMTUUA1/p1707390873404399?thread_ts=1706260647.223059&cid=C01DLMTUUA1) for context.
https://feat-security-categoty-not-yet-cate--docs-codacy.netlify.app/organizations/managing-security-and-risk/#supported-security-categories
=> feat: Clarify the "Not yet categorized" state of security isssues

docs/repositories/commits.md
Fixes the description for the number of Issues shown on the quality overview of [Commits](https://docs.codacy.com/repositories/commits/#quality-overview) and [Pull Requests](https://docs.codacy.com/repositories/pull-requests/#quality-overview).
([internal Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1707998731128409))
- https://fix-description-issues-number--docs-codacy.netlify.app/repositories/commits/#quality-overview
- https://fix-description-issues-number--docs-codacy.netlify.app/repositories/pull-requests/#quality-overview
=> fix: Fix description of shown issues number

docs/release-notes/cloud/cloud-2023-10.md
Adds feature removal to Cloud October 2023 release notes.
https://cy-6604-release-notes-add-feature-r--docs-codacy.netlify.app/release-notes/cloud/cloud-2023-10/#feature-removal
=> fix: Add feature removal to release notes

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md, docs/repositories-configure/removing-your-repository.md, docs/repositories-configure/using-submodules.md
For GitHub organizations, the Codacy GitHub App will exclusively [authenticate as an app installation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) and use installation access tokens for Git operations.
SSH keys will no longer be used as a fallback mechanism, and the repository Administration will be removed from the Codacy GitHub App.
This pull request updates the documentation to consider this product change.
- https://pluto-811-gh-drop-admin-permission--docs-codacy.netlify.app/getting-started/which-permissions-does-codacy-need-from-my-account/
- https://pluto-811-gh-drop-admin-permission--docs-codacy.netlify.app/repositories-configure/removing-your-repository/
- …
=> feat: Remove Administration permissions and SSH keys for GitHub PLUTO-811

docs/account/emails.md, docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Remove references to Google Sign-In
* https://ala-853-doc-remove-google-login-fro--docs-codacy.netlify.app/account/emails/
* https://ala-853-doc-remove-google-login-fro--docs-codacy.netlify.app/getting-started/which-permissions-does-codacy-need-from-my-account/
=> clean: Remove references to Google Sign-In ALA-853

docs/faq/code-analysis/which-metrics-does-codacy-calculate.md, docs/release-notes/cloud/cloud-2023-03.md
Updates/removes links to blog posts that were renamed/deleted.
=> fix: Fix broken link DOCS-668

docs/organizations/integrations/jira-integration.md
Clarifies that Jira retrieves updates once a day also on the Jira integration page (the info is [already present](https://github.com/codacy/docs/blob/3a48577bba3ee2708a0fc6c3e6fd4ee5cec24eeb/docs/organizations/managing-security-and-risk.md?plain=1#L94) on the SRM page)
Note: No Jira task associated. See [Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1711358811856239?thread_ts=1710842346.159819&cid=C8X9SS1H7) for context.
https://feat-clarify-jira-update-interval--docs-codacy.netlify.app/organizations/integrations/jira-integration/#installing-the-jira-integration
=> feat: Clarify Jira update frequency

docs/faq/general/how-does-codacy-support-bitbucket-cloud.md
Adds a missing link to page [How does Codacy support Bitbucket Cloud?](https://docs.codacy.com/faq/general/how-does-codacy-support-bitbucket-cloud/)
https://join-organization-missing-link--docs-codacy.netlify.app/faq/general/how-does-codacy-support-bitbucket-cloud/
=> clean: Add missing link

docs/repositories-configure/managing-branches.md
Clarifies that changing the default branch on the Git provider doesn't change the default branch on Codacy.
https://tce-838-change-default-branch-on-pr--docs-codacy.netlify.app/repositories-configure/managing-branches/
-   [x] Request validation
-   [ ] Wait for feature release (https://github.com/codacy/repository-listener/pull/716 )
-   [ ] Remove **don't merge** label before merging
=> feat: Change default branch on provider has no effect on Codacy TCE-838

docs/repositories-configure/ignoring-files.md
Removes the docs folder from the list of default ignored files.
https://docs-663-remove-docs-from-ignored--docs-codacy.netlify.app/repositories-configure/ignoring-files/#default-ignored-files
=> feat: Remove docs from the default ignored files DOCS-663

docs/organizations/managing-security-and-risk.md
Clarifies now to categorize findings marked as "Not yet categorized".
Matches edits in https://github.com/codacy/codacy-spa/pull/1711
https://tarot-2668-docs-tweak-for-clarity-n--docs-codacy.netlify.app/organizations/managing-security-and-risk/#supported-security-categories
=> feat: Clarify how to categorize "Not yet categorized" findings TAROT-2668

docs/assets/javascripts/extra.js, mkdocs.yml
-  Intercom is not used anymore
-  https://codacy.atlassian.net/browse/PLUTO-929 
=> chore: Remove intercom and use zendesk PLUTO-929

docs/getting-started/supported-languages-and-tools.md
Adds `jscpd` as the Dart duplication analysis tool
https://docs-691-update-supported-tools-tab--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
=> feat: Add jscpd as Dart duplication analysis tool

docs/repositories-configure/configuring-code-patterns.md
Document alternative RuboCop config file `.rubocop-codacy.yml` to prevent issues with references to private gems in the original Rubocop config file `.rubocop.yml`.
https://docs-697-document-alternative-ruboc--docs-codacy.netlify.app/repositories-configure/configuring-code-patterns/#using-your-own-tool-configuration-files
=> feat: Document alternative RuboCop config file DOCS-697

docs/coverage-reporter/uploading-coverage-in-advanced-scenarios.md
Clarify how to get the report name generated by Golang tests in order to upload coverage
=> fix: Clarify how to report coverage for Golang

docs/getting-started/supported-languages-and-tools.md
Adds `jscpd` support for some languages on the Supported languages and tools page.
https://docs-709-duplication-new-languages--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
=> feat: Add jscpd language support DOCS-709

docs/repositories-configure/integrations/github-integration.md
This is not required for the Automatic summary feature but existing Codacy processing will fail.
> The file must start with a line containing a triple dash (---).
It's best to follow the recommendation and avoid that users creating their file for Automatic summaries are then faced with this problem later on.
=> fix: Codacy config file must start with `---`

docs/getting-started/supported-languages-and-tools.md, docs/organizations/managing-security-and-risk.md
Removes the note mentioning a limitation on Ruby 3.1 analysis.
* https://docs-711-remove-limitation-on-ruby--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
* https://docs-711-remove-limitation-on-ruby--docs-codacy.netlify.app/organizations/managing-security-and-risk/
=> feat: Remove limitation on Ruby 3.1 analysis DOCS-711

docs/organizations/managing-security-and-risk.md
Adding docs mentioning proactive SCA scanning with call to action to upgrade to business tier 
=> feat: Add docs for proactive SCA TAROT-2804

docs/account/emails.md, docs/organizations/managing-people.md
=> adding email duplication restriction info accross docs

docs/release-notes/cloud/cloud-2024-11.md, docs/release-notes/index.md, mkdocs.yml
=> release notes november 2024

docs/enterprise-cloud/github-enterprise-cloud.md, docs/organizations/what-are-organizations.md
=> correct bullet points

docs/repositories-configure/configuring-code-patterns.md
=> fix markdownlint config files

docs/enterprise-cloud/github-enterprise-cloud.md, docs/organizations/managing-people.md
=> Adding definition of members and authors

docs/organizations/managing-security-and-risk.md
=> Update pentesting url

docs/getting-started/supported-languages-and-tools.md, docs/release-notes/cloud/cloud-2025-02-adding-ruff-lizard.md, docs/release-notes/cloud/cloud-2025-02.md, docs/release-notes/index.md, mkdocs.yml
=> release notes february 2025

docs/getting-started/integrating-codacy-with-your-git-workflow.md
=> improved doc regarding branch protection rules on github

docs/getting-started/supported-languages-and-tools.md
It turns out that for all supported languages (except PHP/Composer), Trivy can't provide license information unless the dependencies have been dowloaded locally.
This does not necessarily mean we have to build the client's code, as many languages/package managers provide a way to just download the dependencies, but since tools don't have internet access we can't provide license information when we run Trivy like we thought.
Again, except for PHP/Composer, license information will not be provided by running Trivy.
=> fix: Update license scanning support

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v14.1.1.md, mkdocs.yml
Adds auto-generated release notes for Codacy Self-hosted 14.1.1
https://feat-release-notes-self-hosted-14-1--docs-codacy.netlify.app/release-notes/cloud/cloud-v14.1.1/
=> feat: Release notes for Codacy Self-hosted 14.1.1

docs/getting-started/supported-languages-and-tools.md, docs/organizations/managing-security-and-risk.md, docs/repositories-configure/codacy-configuration-file.md, docs/repositories-configure/configuring-code-patterns.md
=> fix some docs

docs/codacy-api/examples/uploading-dast-results.md
=> fix: Improve documentation for DAST reports upload

docs/codacy-guardrails/codacy-guardrails-getting-started.md
Adds detailed steps for Windows WSL setup.
=> Add detailed steps for Windows WSL setup

docs/codacy-api/examples/triggering-dast-scans.md, docs/organizations/managing-security-and-risk.md
=> feat: document DAST api scanning TAROT-3391

docs/codacy-guardrails/codacy-guardrails-getting-started.md
Updates the Guardrails setup steps.
=> doc: Update Guardrails setup steps

docs/faq/code-analysis/can-i-bypass-codacy-status-check.md
Add note regarding bypassing only working for quality gates
=> Add note regarding bypassing affecting quality gates only

docs/release-notes/cloud/cloud-2025-09.md, docs/release-notes/index.md, mkdocs.yml
=> Release Notes September 2025
