.github/workflows/link-checker.yml
The default was 512 (https://github.com/raviqqe/liche#usage).
=> feature: Lower Link Checker concurrent URL requests to 16

.github/workflows/link-checker.yml
=> fix: Update licher command line arguments

.codacy.yml, .github/workflows/codacy-analysis-cli.yml
Followed the instructions provided by @franciscodua on this GitHub issue:
https://github.com/codacy/codacy-eslint/issues/920#issuecomment-733641578
=> toolchain: Enable Codacy GitHub Action

docs/special-thanks.md
=> fix: Small edits and fixes 2020-49

.gitmodules, docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v3.1.0.md, mkdocs.yml
Details about the release on Slack: https://codacy.slack.com/archives/CSSSHAK9N/p1606922386000700
=> feature: Release notes for Codacy Self-hosted 3.1.0

.vale.ini, docs/faq/general/how-can-i-change-or-cancel-my-plan.md
After the extra context in [CY-3270](https://codacy.atlassian.net/browse/CY-3270) we realized that it would be a good idea to mention the new tool [codacy/codacy-usage-report](https://github.com/codacy/codacy-usage-report) in the public documentation.
=> feature: Mention codacy-usage-report in "How to cancel my plan"

.gitmodules, docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v3.1.0.md, docs/release-notes/self-hosted/self-hosted-v3.2.0.md, mkdocs.yml
Details about the release on Slack: https://codacy.slack.com/archives/CSSSHAK9N/p1608131496003800
-  [x] Solve all TODO comments
=> feature: Release notes for Codacy Self-hosted 3.2.0

.gitmodules
Pulls changes from:
- https://github.com/codacy/chart/pull/655
- https://github.com/codacy/codacy-coverage-reporter/pull/277
=> feature: Update chart and codacy-coverage-reporter submodules

.github/workflows/muffet.yml, docs/repositories/issues-view.md
Fixes #399.
Must wait to include changes from:
* https://github.com/codacy/codacy-coverage-reporter/pull/281
* https://github.com/codacy/chart/pull/657
=> fix: Broken links

docs/organizations/roles-and-permissions-for-synced-organizations.md
Fix formatting of table header in "Roles and permissions for synced organizations".
=> style: Fix formatting of table in "Roles and permissions"

.github/workflows/vale.yml
See https://github.com/errata-ai/vale-action/issues/27 for more info.
=> clean: Use new Vale option to only check modified files in pull requests

docs/faq/general/how-does-codacy-support-bitbucket-cloud.md, docs/faq/general/how-does-codacy-support-bitbucket-server.md, docs/faq/general/how-does-codacy-support-gitlab-cloud.md, docs/faq/general/how-does-codacy-support-gitlab-enterprise.md, docs/organizations/what-are-synced-organizations.md
Add see also links to "How does Codacy support ..." pages on the page about organizations:
=> feature: Add see also links to "How does Codacy support ..."

docs/getting-started/getting-started-with-codacy.md
Small tweaks and improvements to the page "Getting started with Codacy".
Fixes https://github.com/codacy/docs/issues/418.
=> edit: Simplify and improve "Getting started with Codacy" DOCS-191

docs/release-notes/cloud/cloud-release-notes-|-30-oct-2019.md
=> fix: Update link to vue-eslint-parser repository

mkdocs.yml
Includes the changes from https://github.com/codacy/codacy-mkdocs-material/pull/18
=> feature: Update submodule codacy-mkdocs-material

docs/faq/general/which-browsers-do-you-support.md
See the following Slack thread for more information:
https://codacy.slack.com/archives/CSPCTRETH/p1613128521000600
=> feature: Update minimum version of Chrome to 67

docs/getting-started/supported-languages-and-tools.md
Adjusts the width of the columns in the table, and pulls the information about calculating the SLOC to the top of the table:
=> style: Tweak "Supported languages and tools"

docs/getting-started/getting-started-with-codacy.md, docs/getting-started/supported-languages-and-tools.md, docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Language edits and tweaks, taking into account the suggestions from #450.
=> style: Perform small language edits

docs/release-notes/cloud/cloud-release-notes-|-30-oct-2019.md
=> fix: Update link with redirect

.github/workflows/mkdocs.yml
Fixes the changes introduced in #483.
=> fix: Update failing MkDocs workflow

.github/workflows/muffet.yml
New feature added on https://github.com/raviqqe/muffet/pull/154.
=> toolchain: Add rate-limit flag to link checker

docs/organizations/organization-overview.md
=> feature: Mark Organization Overview as a paid feature

docs/faq/general/how-does-codacy-support-gitlab-cloud.md
=> fix: Update broken link fragment

docs/release-notes/self-hosted/self-hosted-v3.4.0.md
See https://codacy.atlassian.net/browse/CY-3762 for more context.
=> feature: Mention that ScalaStyle now supports Scala 2.13

docs/codacy-api/adding-repositories-to-codacy-programmatically.md, docs/faq/general/how-do-i-change-my-email-address-in-codacy.md, docs/faq/general/why-cant-i-see-my-organization.md, docs/faq/troubleshooting/we-no-longer-have-access-to-this-repository.md, docs/faq/troubleshooting/why-arent-duplication-metrics-being-calculated.md, docs/faq/troubleshooting/why-cant-i-configure-post-commit-hooks-and-integrations.md, docs/faq/troubleshooting/why-is-my-file-missing.md, docs/organizations/manual-organizations/share-your-repository-with-a-non-codacy-user.md, docs/organizations/organization-overview.md, docs/organizations/what-are-synced-organizations.md, docs/related-tools/local-analysis/running-aligncheck.md, docs/related-tools/local-analysis/running-deadcode.md, docs/related-tools/local-analysis/running-spotbugs.md, docs/release-notes/self-hosted/self-hosted-v3.0.0.md, docs/repositories-configure/integrations/post-commit-hooks.md, docs/repositories-configure/using-submodules.md, docs/repositories/security-monitor.md
As per the Microsoft Style Guide: https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions
This makes the documentation more consistent and makes it easier to find similar sentences / information such as the notes that are specific for Codacy Self-hosted or a Git provider:
> If you're using Codacy Self-hosted ...
=> style: Use common contraction "you're"

docs/getting-started/getting-started-with-codacy.md
Change tip cards in [Getting started with Codacy](https://docs.codacy.com/getting-started/getting-started-with-codacy/) to more appropriate note cards.
=> style: Change tip cards in "Getting started" to notes

.github/workflows/mkdocs.yml
Push [change and deployment data](https://docs.pulse.codacy.com/cli/pushing-data-to-pulse/#using-git) to Pulse.
=> feature: Push deployment data to Pulse

docs/organizations/roles-and-permissions-for-synced-organizations.md
Merged the columns related to configuring analysis
=> clean: Join columns in Permissions table CY-4018

docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v1.0.0.md, docs/release-notes/self-hosted/self-hosted-v1.0.1.md, docs/release-notes/self-hosted/self-hosted-v1.1.0.md, docs/release-notes/self-hosted/self-hosted-v1.2.0.md, docs/release-notes/self-hosted/self-hosted-v1.3.0.md, docs/release-notes/self-hosted/self-hosted-v1.4.0.md, docs/release-notes/self-hosted/self-hosted-v1.5.0.md, docs/release-notes/self-hosted/self-hosted-v2.0.0.md, docs/release-notes/self-hosted/self-hosted-v2.1.0.md, docs/release-notes/self-hosted/self-hosted-v2.1.1.md, docs/release-notes/self-hosted/self-hosted-v2.2.0.md, docs/release-notes/self-hosted/self-hosted-v2.2.1.md, docs/release-notes/self-hosted/self-hosted-v3.0.0.md, docs/release-notes/self-hosted/self-hosted-v3.1.0.md, docs/release-notes/self-hosted/self-hosted-v3.2.0.md, docs/release-notes/self-hosted/self-hosted-v3.3.0.md, docs/release-notes/self-hosted/self-hosted-v3.4.0.md, docs/release-notes/self-hosted/self-hosted-v3.5.0.md
These will be displayed as the RSS feed "summary" for each entry.
=> feature: Add meta descriptions for Self-hosted release notes DOCS-111

docs/codacy-api/using-the-codacy-api.md, mkdocs.yml
Suggestion from Mark:
https://codacy.slack.com/archives/C011BCR2RN3/p1617903101007100?thread_ts=1617902706.004400&cid=C011BCR2RN3
=> clean: Be more assertive in recommending the new API v3 DOCS-111

mkdocs.yml
Includes the changes from https://github.com/codacy/codacy-mkdocs-material/pull/36.
=> clean: Update codacy-mkdocs-material submodule

.github/workflows/mkdocs.yml
Followed the syntax in https://developers.google.com/search/docs/advanced/robots/robots_txt.
=> clean: Clean robots.txt and include sitemap URL

.github/workflows/mkdocs.yml
As recommended [here](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow).
=> fix: Protect secret.PULSE_TOKEN using an environment variable

docs/getting-started/supported-languages-and-tools.md
Be more explicit about the fact that Codacy now supports cloud infrastructure-as-code frameworks, providing static analysis to enforce security and compliance best practices.
=> feature: Emphasize support for cloud infrastructure-as-code CY-3949

docs/codacy-api/api-tokens.md
Improve consistency for section titles that include tasks / procedural information.
=> clean: Improve section titles for API tokens

requirements.txt
Fixes issue solved in https://github.com/prcr/mkdocs-meta-descriptions-plugin/pull/50.
=> bump: Update meta-descriptions plugin to 0.0.4

.github/workflows/muffet.yml
Experiment to see if this change reduces the reported false positives.
=> toolchain: Lower rate limiting for weekly broken link check

mkdocs.yml
Update all submodules and the chart version in `mkdocs.yml` to update the **Latest** version of the documentation with the new Codacy Self-hosted 4.0.0 release.
=> feature: Update all submodules and chart version

.github/styles/Vocab/Codacy/accept.txt, docs/release-notes/index.md, docs/release-notes/self-hosted/self-hosted-v4.0.0.md, mkdocs.yml
Preview of the release notes page:
https://github.com/codacy/docs/blob/feature/self-hosted-release-notes-4.0.0/docs/release-notes/self-hosted/self-hosted-v4.0.0.md
=> Add release notes for SH 4.0.0

docs/release-notes/cloud/deprecating-http-headers-for-api-tokens.md
=> fix: Update broken link to NGINX wiki

mkdocs.yml
Updates the Latest documentation with the new Codacy Self-hosted version 4.0.1.
=> feature: Update chart version and submodule

docs/repositories-configure/managing-branches.md
Quick cleanup and refactor of the information on the page [Managing branches](https://docs.codacy.com/repositories-configure/managing-branches/).
=> clean: Refactor Managing branches

CONTRIBUTING.md, docs/faq/general/how-does-codacy-support-gitlab-cloud.md, docs/faq/general/how-does-codacy-support-gitlab-enterprise.md, docs/getting-started/codacy-quickstart.md, docs/getting-started/getting-started-with-codacy.md, docs/getting-started/supported-languages-and-tools.md, docs/index.md, docs/organizations/managing-people.md, mkdocs.yml
I saw another documentation site that included the time next to the quickstart page title and thought that it could also be a good idea to promote how fast (and simple) it is to try out Codacy. What do you think?
-   [x] Rename source file name and update references
=> feature: Highlight that getting started with Codacy is very fast

docs/organizations/manual-organizations/creating-and-renaming-an-organization.md
Workaround for https://github.com/prcr/mkdocs-meta-descriptions-plugin/issues/95.
=> fix: Add meta description to "Creating and renaming an organization"

netlify.toml
Tries to make the configuration added in https://github.com/codacy/docs/pull/821 work.
=> toolchain: Update netlify.toml syntax to ignore builds on master

docs/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed.md, docs/faq/repositories/how-do-i-manually-force-a-repository-update.md, mkdocs.yml
Merged the information from that page with the related page troubleshooting page "How long does it take for my repository to be analyzed?"
=> clean: Remove page "How do I manually force a repository update?"

docs/release-notes/index.md
Helps clarify how users can get updates using the RSS feed.
=> feature: Mention news aggregator to subscribe to RSS feed

docs/assets/includes/legacy-organizations-important.md, docs/organizations/manual-organizations/administrative-permissions.md, docs/organizations/manual-organizations/creating-and-managing-teams.md, docs/organizations/manual-organizations/creating-and-renaming-an-organization.md, docs/organizations/manual-organizations/managing-team-repositories.md, docs/organizations/manual-organizations/share-your-repository-with-a-non-codacy-user.md, docs/release-notes/cloud/cloud-2021-11-02-legacy-organizations.md, docs/release-notes/index.md, mkdocs.yml
Live preview of the announcement page:
https://deploy-preview-869--docs-codacy.netlify.app/release-notes/cloud/cloud-2021-11-02-legacy-organizations/
Blocks [CY-5037](https://codacy.atlassian.net/browse/CY-5037).
=> feature: Announce end of support for legacy organizations CY-4234

docs/account/emails.md
This is to improve the consistency across all pages.
=> clean: Edit UI path for Emails page

docs/repositories-configure/adjusting-quality-settings.md, docs/repositories/repository-dashboard.md
Applies the feedback provided by @RaquelHipolito on https://github.com/codacy/docs/pull/907.
Live preview:
https://deploy-preview-913--docs-codacy.netlify.app/repositories-configure/adjusting-quality-settings
=> clean: Apply feedback to Adjusting quality settings CY-5188

docs/repositories/files.md
=> feature: Mention sorting the files list CY-5255

docs/repositories/files.md
=> feature: Mention that files list is sorted alphabetically by default CY-5255

docs/organizations/using-a-coding-standard.md
Since there will also be a filter for the recommended configurations, the sentence can be simplified a bit because it can act as the description of one of the possible filters.
=> clean: Simplify description of recommended configurations CY-4956

.github/workflows/calibre.yml
Uses the GitHub Action https://github.com/marketplace/actions/image-actions
=> toolchain: Optimize images in pull requests using Image Actions

tools/README.md, tools/list-last-modified.py, tools/requirements.txt
Adds script that outputs the last modified date of each documentation page as a CSV file.
https://github.com/codacy/docs/blob/toolchain/list-last-changed-dates-DOCS-164/tools/README.md#list-last-modified
=> toolchain: List last modified page dates DOCS-164

docs/codacy-api/api-tokens.md
Addresses the feedback from @pedrocodacy: https://github.com/codacy/docs/pull/976#discussion_r778035753
=> clean: Edit sentence mentioning project API tokens limit CY-5355

docs/organizations/organization-overview.md
Mentions the existing limit of the Organization Overview that displays information only for the last 100 updated repositories.
https://deploy-preview-1019--docs-codacy.netlify.app/organizations/organization-overview
=> feature: Add limit of 100 repositories on Organization Overview CY-5623

docs/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate.md
Configuring Codacy in a way that is perceived as blocking the progress of developers may inadvertently create adoption challenges. This pull request aims to mitigate that by providing guidance on what to consider when configuring quality gates for the first time.
https://deploy-preview-1013--docs-codacy.netlify.app/faq/general/how-do-i-block-merging-prs-using-codacy-as-a-quality-gate/#configuring-gate
=> feature: Add guidance on initial set up of quality gates DOCS-342

.github/workflows/mkdocs.yml
Makes the message more consistent with the one from mike.
=> toolchain: Adjust commit message when deploying Latest DOCS-243

.github/workflows/mkdocs.yml
Applies the same simplification as in https://github.com/codacy/pulse-user-docs/pull/95.
=> toolchain: Bump actions/setup-python and simplify workflow

docs/repositories-configure/integrations/jira-integration.md
Detected on https://github.com/codacy/docs/issues/1042
=> fix: Update link to Atlassian documentation

docs/getting-started/codacy-quickstart.md
Adds the product demo video developed by Customer Success to the intro of the Codacy quickstart page.
https://deploy-preview-1098--docs-codacy.netlify.app/getting-started/codacy-quickstart/
=> feature: Embed Customer Success product demo on Codacy quickstart

docs/getting-started/codacy-quickstart.md
This will help both the users and ourselves keep track of the most current version of the video, as we intend to update it regularly.
https://deploy-preview-1102--docs-codacy.netlify.app/getting-started/codacy-quickstart
=> clean: Include product demo recording date

mkdocs.yml, requirements.txt
Now that mkdocs-monorepo-plugin [fixed a bug](https://github.com/codacy/docs/pull/1136) affecting the `edit_url` of the included documentation pages, it's possible to enable a link on each documentation page to allow users to quickly edit the corresponding source file:
https://deploy-preview-1140--docs-codacy.netlify.app/getting-started/codacy-quickstart/#all-set
- https://github.com/codacy/codacy-coverage-reporter/pull/367
- https://github.com/codacy/chart/pull/726
- https://github.com/codacy/codacy-mkdocs-material/pull/51
=> feature: Enable edit button on documentation pages

.github/workflows/mkdocs.yml
Small adjustments on top of #1166.
=> toolchain: Adjust GitHub Action for branch previews on Netlify

docs/faq/repositories/how-do-i-reanalyze-my-repository.md
=> clean: Clarify meaning of greyed out badges and grades

.github/pull_request_template.md
Adjust the headings in the pull request template so that they aren't so prominent in the pull request description.
=> clean: Adjust headings in pull request template

docs/getting-started/supported-languages-and-tools.md
=> style: Update anchor link for Suggested fixes

docs/codacy-api/using-the-codacy-api.md
Small improvements to clarify how to use the API endpoint pagination.
https://clean-improve-using-api-pagination--docs-codacy.netlify.app/codacy-api/using-the-codacy-api/#using-pagination
=> clean: Improve instructions on how to use API pagination

docs/codacy-api/api-tokens.md, docs/codacy-api/using-the-codacy-api.md
Adds the Codacy API rate limit that we have in place and recommends how developers should work around the rate limit.
https://feature-api-rate-limits-docs-370--docs-codacy.netlify.app/codacy-api/using-the-codacy-api/#request-rate-limit
=> feature: Add Codacy API rate limits DOCS-370 CY-5907

tools/check-security-tools.py
Updates `check-security-tools.py` to fetch 1000 code patterns on each API call to reduce the time it takes to run the script.
=> toolchain: Fetch 1000 code patterns at a time in check-security-tools.py

tools/README.md, tools/get-security-patterns.py
Adds a script to output the details of all supported security code patterns as a CSV file.
=> toolchain: Output details of all security code patterns DOCS-340

docs/repositories/security-monitor.md
Reviewed and improved descriptions for the currently supported security categories.
https://feature-update-security-categories--docs-codacy.netlify.app/repositories/security-monitor/#supported-security-categories
- https://github.com/codacy/codacy-tools/pull/496
- https://github.com/codacy/codacy-worker/pull/116
=> feature: Update security category descriptions DOCS-340

docs/getting-started/supported-languages-and-tools.md, docs/related-tools/codacy-plugin-tools.md, docs/repositories-configure/codacy-configuration-file.md, docs/special-thanks.md
Fixes https://github.com/codacy/docs/issues/1283.
- https://github.com/codacy/codacy-coverage-reporter/pull/394
- https://github.com/codacy/chart/pull/739
=> fix: Update broken links

docs/organizations/organization-overview.md, docs/repositories/repository-dashboard.md
Improves the consistency and maintainability of the introduction for
the Repository Dashboard and Organization Overview pages.
https://clean-improve-dashboard-overview-co--docs-codacy.netlify.app/repositories/repository-dashboard/
https://clean-improve-dashboard-overview-co--docs-codacy.netlify.app/organizations/organization-overview/
=> clean: Improve Repository Dashboard and Organization Overview intros

CONTRIBUTING.md
Reviews and expands the new instructions on how to make changes to submodules added in https://github.com/codacy/docs/pull/1442.
https://github.com/codacy/docs/blob/clean/edit-contributing/CONTRIBUTING.md#making-changes-to-submodules
=> clean: Review and expand instructions on how to update submodules

docs/faq/code-analysis/why-does-codacy-show-unexpected-coverage-changes.md
Small edit to avoid passive voice.
=> clean: Edit examples intro to avoid passive voice DOCS-413

docs/repositories/commits.md
See https://github.com/codacy/codacy-website/pull/314#discussion_r1026571060 for context.
- https://fix-quality-overview-clarify-gray-c--docs-codacy.netlify.app/repositories/pull-requests/#quality-overview
- https://fix-quality-overview-clarify-gray-c--docs-codacy.netlify.app/repositories/commits/#quality-overview
=> fix: Clarify meaning of gray values on the quality overview CY-6590

docs/getting-started/codacy-quickstart.md
Goal: to improve the Quickstart guide with a concise and appealing introduction to Codacy, what it does, and the value it provides. 
https://feat-improve-quickstart-intro-docs--docs-codacy.netlify.app/getting-started/codacy-quickstart/#codacy-quickstart-5-min
- Consider splitting the new block in 2, before and after the intro video, to prevent the copy from pushing the video below the fold
- As an alternative, consider shortening the copy
=> feat: Improve Quickstart with an introduction on Codacy DOCS-369

docs/repositories-configure/managing-branches.md
Hotfix, see https://github.com/codacy/docs/pull/1576#discussion_r1071953902
=> fix: Update sentence on the Managing Branches page DOCS-497

docs/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed.md
List factors impacting analysis times to set customer expectations.
https://feat-clarify-analysis-duration-docs--docs-codacy.netlify.app/faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed/
=> feat: Clarify reasons for long analysis times DOCS-407

docs/faq/general/how-does-codacy-support-gitlab-cloud.md, docs/faq/general/how-does-codacy-support-gitlab-enterprise.md, docs/getting-started/codacy-quickstart.md
Improves quickstart titles based on [internal feedback](https://codacy.atlassian.net/browse/DOCS-470?focusedCommentId=54148).
=> feat: Improve quickstart titles DOCS-470

docs/coverage-reporter/index.md
Closes https://github.com/codacy/docs/issues/1622
=> fix: Fix broken link

docs/coverage-reporter/index.md
Add a new reason for encountering a "Pending" status after uploading a coverage report
https://feat-new-pending-status-reason-cove--docs-codacy.netlify.app/coverage-reporter/#status-pending
=> feat: Update the table detailing a Pending coverage report status DOCS-522

docs/getting-started/integrating-codacy-with-your-git-workflow.md
Fixes a small inconsistency in the way we were capitalizing text in list items after the colons.
https://style-remove-capitalization--docs-codacy.netlify.app/getting-started/integrating-codacy-with-your-git-workflow/#blocking-pull-requests
=> style: Fix capitalization after colon

CONTRIBUTING.md
Fixes a small typo on "check out".
=> fix: Fix typo on CONTRIBUTING.md

docs/faq/general/how-does-codacy-protect-my-privacy.md
Small update to take into account that the GDPR is already in place ([reported by Mark](https://codacy.slack.com/archives/DSVH3G2BY/p1678278053257339)).
https://fix-gdpr-past-date--docs-codacy.netlify.app/faq/general/how-does-codacy-protect-my-privacy/
=> fix: Fix reference to future GDPR implementation date

CONTRIBUTING.md
Updates CONTRIBUTING.md with the new process for creating new Codacy Self-hosted documentation versions. See [DOCS-543](https://codacy.atlassian.net/browse/DOCS-543) for more details.
[DOCS-543]: https://codacy.atlassian.net/browse/DOCS-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: Update instructions for releasing Codacy Self-hosted docs versions DOCS-543

docs/repositories-configure/configuring-code-patterns.md
As [identified here](https://github.com/codacy/docs/pull/1736#discussion_r1202410294).
=> fix: Remove spurious space DOCS-560

docs/repositories-configure/ignoring-files.md
Explain how to override the default list of ignored files
https://feat-override-default-ignored-files--docs-codacy.netlify.app/repositories-configure/ignoring-files/#default-ignored-files
=> feat: Explain how to override default ignored files DOCS-564

.github/workflows/deleted-files.yml
Detects deleted Markdown files and posts a reminder to the PR thread.
TODO:
=> toolchain: Update GH actions to detect deleted and renamed files DOCS-535

docs/assets/includes/preview.md, docs/repositories-configure/integrations/bitbucket-integration.md, docs/repositories-configure/integrations/github-integration.md, docs/repositories-configure/integrations/gitlab-integration.md
Removes the admonition for general availability of the feature.
* https://feat-ai-prelaunch-tweaks-hrz-302--docs-codacy.netlify.app/repositories-configure/integrations/github-integration/
* https://feat-ai-prelaunch-tweaks-hrz-302--docs-codacy.netlify.app/repositories-configure/integrations/gitlab-integration/
* https://feat-ai-prelaunch-tweaks-hrz-302--docs-codacy.netlify.app/repositories-configure/integrations/bitbucket-integration/
=> clean: Remove "under development" admonition HRZ-302

docs/organizations/managing-security-and-risk.md
Tweaks the copy in preparation for the edits in https://github.com/codacy/docs/pull/1797/files
=> feat: Dashboard filters prep PUL-2148

docs/organizations/managing-security-and-risk.md
Updates SRM data retention policies
https://feat-srm-data-retention-pul-2190--docs-codacy.netlify.app/organizations/managing-security-and-risk/#data-retention
=> feat: Clarify SRM data retention policies PUL-2190

docs/organizations/managing-security-and-risk.md
Small tweak to clarify the meaning of a sentence.
https://fix-improve-wording-pul-2190--docs-codacy.netlify.app/organizations/managing-security-and-risk/#data-retention
=> fix: Improve data retention wording PUL-2190

docs/organizations/roles-and-permissions-for-organizations.md
=> clean: Remove old TODO

.github/workflows/readability.yml
Tests readability report GH action
=> feat: Add GH action - readability report

docs/getting-started/which-permissions-does-codacy-need-from-my-account.md
Update the GitHub permission table with the new Repository Contents permission
https://ala-619-doc-announce-and-explain-ne--docs-codacy.netlify.app/getting-started/which-permissions-does-codacy-need-from-my-account/#github-cloud
=> feat: Update the GitHub permission table ALA-619

docs/repositories/issues.md
=> clean: Remove old TODOs

docs/organizations/roles-and-permissions-for-organizations.md
Update table cell backgrounds to improve readability.
https://tarot-2439-doc-org-managers-post-re--docs-codacy.netlify.app/organizations/roles-and-permissions-for-organizations/#permissions-for-github
=> feat: Update table cell backgrounds TAROT-2439

docs/release-notes/cloud/cloud-2023-11-23-new-coverage-engine-status-checks.md
[See Slack](https://codacy.slack.com/archives/CA5GWEXSN/p1702640011599649?thread_ts=1702578148.626289&cid=CA5GWEXSN) for context.
=> feat: Add instruction to review and accept updated permissions

docs/organizations/roles-and-permissions-for-organizations.md
Clarify the repository configuration permissions.
https://docs-658-clarify-permission--docs-codacy.netlify.app/organizations/roles-and-permissions-for-organizations/
=> clean: Clarify the repository configuration permission DOCS-658

docs/organizations/managing-security-and-risk.md
Updates a footnote following an internal request ([thread](https://codacy.slack.com/archives/C011BCR2RN3/p1709559046185129))
https://feat-update-srm-plugins--docs-codacy.netlify.app/organizations/managing-security-and-risk/#eslint-plugin
=> feat: Update footnote

docs/assets/javascripts/extra.js, mkdocs.yml
This reverts https://github.com/codacy/docs/pull/2090
=> Revert "chore: Remove intercom and use zendesk PLUTO-929 (#2090)"

docs/organizations/managing-security-and-risk.md
Removes mentions of "scan kind" since the feature is still in development.
https://fix-scan-kind--docs-codacy.netlify.app/organizations/managing-security-and-risk/#open-findings-distribution
=> fix: Temporarily remove mention of scan kind

docs/assets/javascripts/extra.js, docs/organizations/managing-security-and-risk.md, mkdocs.yml
Replace Intercom-related assets with Zendesk
https://docs-683-replace-intercom-with-zend--docs-codacy.netlify.app/
=> feat: Replace Intercom with Zendesk DOCS-683

docs/repositories-configure/configuring-code-patterns.md
Fixes suggested order of config files
=> feat: Fix order DOCS-697

docs/release-notes/self-hosted/self-hosted-v14.0.0.md
Adds a missing link to release notes
=> feat: Add missing Credo link

docs/getting-started/supported-languages-and-tools.md
=> TCE-1005: Update supported-languages-and-tools.md

docs/getting-started/supported-languages-and-tools.md
Updates the list of languages scanned for SCA (software composition analysis / dependency vulnerability scanning)
https://docs-713-update-list-of-languages-s--docs-codacy.netlify.app/getting-started/supported-languages-and-tools/
=> feat: Update languages scanned for SCA DOCS-713

docs/repositories-configure/configuring-code-patterns.md
=> Update Bandit list of configuration files

docs/repositories-configure/codacy-configuration-file.md
=> fix typo sonarscharp

docs/organizations/using-coding-standards.md
https://feature-multiple-standards-ala-1140--docs-codacy.netlify.app/organizations/using-coding-standards/
-   [ ] Update screenshots
Updating screenshots on the follow up PR
=> feature: multiple standards support ALA-1140

docs/organizations/using-coding-standards.md
=> fix: better explain pattern priority in case of multiple standards

docs/organizations/managing-security-and-risk.md
See Slack thread: https://codacy.slack.com/archives/C8X9SS1H7/p1724947183805949
=> clean: Clarification about security subcategories

docs/repositories-configure/configuring-code-patterns.md
@alerizzo Can you take care of screenshots?
(https://feature-update-configure-patterns-a--docs-codacy.netlify.app)
=> feature: update configure patterns ALA-1207

docs/organizations/using-coding-standards.md
=> docs: Add section about repository-level configurations when coding standards are applied ALA-1207

docs/release-notes/cloud/cloud-2024-08.md, docs/release-notes/index.md, mkdocs.yml
=> feat: Release notes for Codacy Cloud August 2024

.github/workflows/jira.yml, .github/workflows/mkdocs.yml, .github/workflows/scheduled.yml, .github/workflows/vale.yml, requirements.txt
=> upgrade versions workflows and requirements.txt

docs/release-notes/index.md
=> fix list of codacy release notes

requirements.txt
=> downgrade mkdocs packages

docs/release-notes/cloud/cloud-2024-09.md, docs/release-notes/index.md, mkdocs.yml
=> release notes September

docs/repositories/issues.md
=> clean: Update issue card details

docs/getting-started/supported-languages-and-tools.md
=> improve supported languages to describe duplication and complexity tools

docs/release-notes/cloud/cloud-2024-12.md, docs/release-notes/index.md, mkdocs.yml
=> release notes December 2024

docs/organizations/managing-security-and-risk.md
=> Remove Dependency to Pro reference in Dependencies section

docs/getting-started/supported-languages-and-tools.md
=> change duplication tool for java

docs/getting-started/integrating-codacy-with-your-git-workflow.md
Add details for the levels of branch protection
https://protection-rules-help--docs-codacy.netlify.app/getting-started/integrating-codacy-with-your-git-workflow/#blocking-pull-requests
=> Add details for the levels of branch protection ALA-1423

tools/check-security-tools.py, tools/check-supported-tools.py
=> add pmd7 and eslint9 to the workflows

docs/getting-started/supported-languages-and-tools.md, docs/organizations/managing-security-and-risk.md
=> feature: Add supported languages for license scanning TAROT-3190

docs/organizations/audit-logs-for-organizations.md
See https://github.com/codacy/codacy-website/pull/1747
=> feature: Add audit logging information for DAST analysis endpoint

docs/release-notes/cloud/cloud-2025-03.md, docs/release-notes/index.md, mkdocs.yml
=> release notes march 2025

docs/getting-started/supported-languages-and-tools.md, docs/repositories-configure/local-analysis/running-dartanalyzer.md
=> add dartanalyzer on the pipeline docs and uv.lock as supported file

docs/getting-started/supported-languages-and-tools.md, docs/repositories-configure/local-analysis/running-dartanalyzer.md, mkdocs.yml
=> Update client side tools docs (fix navigation)

docs/codacy-api/examples/triggering-dast-scans.md
- format important note to add paragraphs
- make TARGET API ID a list item
- minor wording tweaks
- remove auth from first note since its present on all examples
=> fix: review formatting in dast api docs

docs/release-notes/cloud/cloud-2025-04.md, docs/release-notes/index.md, mkdocs.yml
=> release notes april 2025

docs/getting-started/supported-languages-and-tools.md, docs/release-notes/cloud/cloud-2025-05.md, docs/release-notes/index.md, mkdocs.yml
=> Release Notes May 2025

docs/getting-started/supported-languages-and-tools.md
=> chore: update tools regarding licensing

docs/organizations/managing-security-and-risk.md
=> fix: Nested bullets indentation

docs/getting-started/supported-languages-and-tools.md
=> chore: add python licenses

docs/enterprise-cloud/github-enterprise-cloud.md
=> Add GitHub Cloud Data Residency Limitation Documentation - LK-1573

docs/codacy-guardrails/codacy-guardrails-faq.md
=> fix typo on guardrails docs

docs/getting-started/integrating-codacy-with-your-git-workflow.md
=> fix: Remove unnecessary warning about GH pipelines
